"""
OCTON VAR — 20 canonical VAR precedents.
Bootstraps the training corpus so the AI has binding precedent on day one.
Each case carries: title, incident_type, correct_decision, rationale, keywords,
tags, match_context, law_references, outcome.
"""
CANONICAL_CASES = [
    # ── Offside (4) ─────────────────────────────────────────
    {
        "title": "Armpit Offside - Sterling vs Villarreal",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside",
        "rationale": "Attacker's armpit was fractionally beyond the last defender at the moment the ball was played. Marginal but conclusive on semi-automated offside lines.",
        "keywords": ["semi-automated", "armpit", "marginal", "last defender", "through ball", "goal scored", "calibrated line"],
        "tags": ["marginal-offside", "semi-automated", "goal-disallowed"],
        "match_context": {"teams": "Man City vs Villarreal", "competition": "UEFA Champions League", "year": 2021},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal overturned",
    },
    {
        "title": "Played Onside by Defender - Alexander-Arnold",
        "incident_type": "offside",
        "correct_decision": "Onside - Goal Stands",
        "rationale": "Attacker appeared in an offside position but was played onside by a deliberate clearance from a defender. Deliberate play resets the offside phase.",
        "keywords": ["played onside", "deliberate clearance", "defender", "reset phase", "onside"],
        "tags": ["onside", "deliberate-play", "goal-stands"],
        "match_context": {"teams": "Liverpool vs Tottenham", "competition": "Premier League", "year": 2019},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal confirmed",
    },
    {
        "title": "Clear Daylight Offside - Set Piece Line",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside",
        "rationale": "Striker was more than a metre beyond the last defender when the ball was played. No interpretation needed — unambiguous call.",
        "keywords": ["daylight", "clear offside", "striker beyond", "metre beyond", "unambiguous"],
        "tags": ["clear-offside", "daylight", "goal-disallowed"],
        "match_context": {"teams": "Real Madrid vs Valencia", "competition": "La Liga", "year": 2022},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal overturned",
    },
    {
        "title": "Offside from Corner — Not Applicable",
        "incident_type": "offside",
        "correct_decision": "Onside - Goal Stands",
        "rationale": "There is no offside offence from a corner kick regardless of attacker position. On-field flag should be withdrawn.",
        "keywords": ["corner kick", "no offside", "not applicable", "header goal", "corner"],
        "tags": ["no-offside-rule", "corner", "goal-stands"],
        "match_context": {"teams": "Arsenal vs Chelsea", "competition": "Premier League", "year": 2020},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal confirmed",
    },

    # ── Handball (4) ────────────────────────────────────────
    {
        "title": "Arm Extended Away from Body - Goal Ruled Out",
        "incident_type": "handball",
        "correct_decision": "Handball - Goal Disallowed",
        "rationale": "Attacker's arm was clearly extended away from the body to intercept, making the body unnaturally bigger prior to scoring. Attacking-phase handball rule applies.",
        "keywords": ["arm extended", "body bigger", "attacking handball", "disallow goal", "unnatural"],
        "tags": ["arm-extended", "body-bigger", "attacking-handball", "goal-disallowed"],
        "match_context": {"teams": "France vs Tunisia", "competition": "World Cup", "year": 2022},
        "law_references": ["IFAB Law 12"],
        "outcome": "goal overturned",
    },
    {
        "title": "Ball-to-Hand from Close Range — No Handball",
        "incident_type": "handball",
        "correct_decision": "No Handball - Natural Position",
        "rationale": "Ball struck defender's arm from close range with the arm in a natural position by the side. No deliberate movement toward the ball.",
        "keywords": ["ball to hand", "close range", "natural position", "by the side", "deflection", "no handball"],
        "tags": ["ball-to-hand", "natural-position", "no-handball"],
        "match_context": {"teams": "Juventus vs Inter", "competition": "Serie A", "year": 2021},
        "law_references": ["IFAB Law 12"],
        "outcome": "play on",
    },
    {
        "title": "Handball in Box — Penalty",
        "incident_type": "handball",
        "correct_decision": "Penalty Awarded - Handball",
        "rationale": "Defender slid with arm fully extended outside body line to block the shot inside the penalty area. Clear handball offence, deliberate act of making body bigger.",
        "keywords": ["arm extended", "inside box", "blocked shot", "sliding", "body bigger", "penalty"],
        "tags": ["inside-box", "arm-extended", "blocked-shot", "penalty"],
        "match_context": {"teams": "Barcelona vs Sevilla", "competition": "La Liga", "year": 2023},
        "law_references": ["IFAB Law 12", "IFAB Law 14"],
        "outcome": "penalty awarded",
    },
    {
        "title": "Deflection off own Body to Arm — No Handball",
        "incident_type": "handball",
        "correct_decision": "No Handball - Own Body Deflection",
        "rationale": "Ball deflected off attacker's thigh onto his own arm immediately before scoring. Per 2021 IFAB amendment, only deliberate handball by scorer is penalised; accidental contact off own body is not.",
        "keywords": ["own body", "deflection", "thigh", "accidental", "scorer", "own arm"],
        "tags": ["own-body-deflection", "accidental", "goal-stands"],
        "match_context": {"teams": "Bayern vs Leipzig", "competition": "Bundesliga", "year": 2022},
        "law_references": ["IFAB Law 12"],
        "outcome": "goal confirmed",
    },

    # ── Foul / Penalty (4) ──────────────────────────────────
    {
        "title": "Tactical Foul Stopping Counter — Yellow Card",
        "incident_type": "foul",
        "correct_decision": "Yellow Card - Stopping Promising Attack",
        "rationale": "Defender committed a cynical trip near halfway line as attacker broke forward with numerical advantage. Stopping a promising attack = mandatory yellow.",
        "keywords": ["tactical foul", "counter-attack", "promising attack", "cynical", "yellow card", "trip", "halfway"],
        "tags": ["tactical-foul", "stopping-promising-attack", "yellow-card"],
        "match_context": {"teams": "Man Utd vs Liverpool", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "yellow card issued",
    },
    {
        "title": "Penalty - Trip Inside the Area",
        "incident_type": "penalty",
        "correct_decision": "Penalty Awarded",
        "rationale": "Defender made contact with attacker's trailing leg inside the penalty area with no prior touch on the ball. Clear trip, penalty and no card (not DOGSO).",
        "keywords": ["trip", "inside box", "penalty area", "trailing leg", "no ball contact", "penalty"],
        "tags": ["trip", "inside-box", "penalty", "no-card"],
        "match_context": {"teams": "PSG vs Marseille", "competition": "Ligue 1", "year": 2022},
        "law_references": ["IFAB Law 14"],
        "outcome": "penalty awarded",
    },
    {
        "title": "Simulation - Dive in Penalty Area",
        "incident_type": "penalty",
        "correct_decision": "No Penalty - Simulation, Yellow Card Attacker",
        "rationale": "Attacker initiated contact and went down theatrically with no meaningful defender contact. Simulation is sanctioned with a yellow card.",
        "keywords": ["dive", "simulation", "theatrical", "no contact", "initiated contact", "yellow card attacker"],
        "tags": ["simulation", "dive", "yellow-attacker", "no-penalty"],
        "match_context": {"teams": "Dortmund vs Leipzig", "competition": "Bundesliga", "year": 2021},
        "law_references": ["IFAB Law 14"],
        "outcome": "yellow to attacker",
    },
    {
        "title": "Holding Inside Box at Corner — Penalty",
        "incident_type": "penalty",
        "correct_decision": "Penalty Awarded - Shirt Pull",
        "rationale": "Defender grabbed attacker's shirt and pulled him to ground inside the area from a corner kick. Persistent holding offences in the box must be penalised.",
        "keywords": ["holding", "shirt pull", "corner kick", "inside box", "persistent", "grabbed shirt"],
        "tags": ["holding", "shirt-pull", "corner", "penalty"],
        "match_context": {"teams": "Atletico vs Real Madrid", "competition": "La Liga", "year": 2022},
        "law_references": ["IFAB Law 14"],
        "outcome": "penalty awarded",
    },

    # ── Red Card (4) ────────────────────────────────────────
    {
        "title": "Studs-Up Serious Foul Play — Red Card",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Serious Foul Play",
        "rationale": "Tackle made with studs up, at speed, above the ankle with excessive force — endangering the opponent's safety. Mandatory red card.",
        "keywords": ["studs up", "high boot", "excessive force", "endanger safety", "serious foul play", "red card"],
        "tags": ["studs-up", "serious-foul-play", "excessive-force", "red-card"],
        "match_context": {"teams": "Chelsea vs Arsenal", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "DOGSO — Professional Foul Outside Box",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Denying Obvious Goal-Scoring Opportunity",
        "rationale": "Last defender tripped attacker who was clean through on goal with no cover. DOGSO mandates red card (outside penalty area, no attempt to play ball).",
        "keywords": ["last defender", "DOGSO", "clear through", "professional foul", "no cover", "red card"],
        "tags": ["DOGSO", "last-defender", "red-card"],
        "match_context": {"teams": "Spurs vs Newcastle", "competition": "Premier League", "year": 2022},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "Violent Conduct Off the Ball — Red Card",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Violent Conduct",
        "rationale": "Player struck opponent with elbow off the ball in an aerial duel — deliberate, excessive force, not a genuine challenge. Violent conduct = red.",
        "keywords": ["elbow", "off the ball", "violent conduct", "aerial duel", "struck opponent", "deliberate"],
        "tags": ["violent-conduct", "elbow", "off-ball", "red-card"],
        "match_context": {"teams": "AC Milan vs Napoli", "competition": "Serie A", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "Reckless but Not Excessive — Yellow not Red",
        "incident_type": "red_card",
        "correct_decision": "Yellow Card - Reckless Challenge",
        "rationale": "Challenge was late and reckless but did not use excessive force or endanger safety. Yellow is appropriate; red would exceed the threshold.",
        "keywords": ["reckless", "late tackle", "not excessive", "yellow card", "not endangering"],
        "tags": ["reckless", "yellow-card", "not-serious-foul"],
        "match_context": {"teams": "Brentford vs Wolves", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "yellow card issued",
    },
    {
        "title": "Physical Contact With Referee — Automatic Violent Conduct",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Violent Conduct (Referee Contact)",
        "rationale": "Any deliberate physical contact with a match official (push, shove, grab, strike, headbutt, kick, spit) is automatic violent conduct under IFAB Law 12. No discretion, no 'clear and obvious' threshold — straight red card. Confidence must be very high whenever the description explicitly states the player made contact with the referee, assistant referee or 4th official.",
        "keywords": ["pushed referee", "shoved referee", "grabbed referee", "struck referee", "referee contact", "physical contact official", "angry player", "aggression toward referee", "howled referee", "contact with linesman", "violent conduct official"],
        "tags": ["violent-conduct", "referee-contact", "automatic-red", "no-discretion", "red-card"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12 (binding)", "year": 2024},
        "law_references": ["IFAB Law 12", "IFAB Law 5"],
        "outcome": "red card issued",
    },
    {
        "title": "Stamping on Opponent — Serious Foul Play Red",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Serious Foul Play (Stamping)",
        "rationale": "Player deliberately stamped on opponent's leg/ankle while ball was not in playable range. Stamping uses excessive force and endangers the opponent's safety — mandatory red.",
        "keywords": ["stamped on", "stamp", "stamping", "endangered safety", "ball not playable", "excessive force"],
        "tags": ["stamping", "serious-foul-play", "excessive-force", "red-card"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "Spitting at Opponent — Violent Conduct Red",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Violent Conduct (Spitting)",
        "rationale": "Spitting at any person (opponent, team-mate, match official, spectator) is automatic violent conduct under IFAB Law 12. Straight red card with no discretion.",
        "keywords": ["spat at", "spat on", "spit at", "spitting", "violent conduct", "automatic red"],
        "tags": ["spitting", "violent-conduct", "automatic-red", "red-card"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },

    # ── Goal Line (2) ───────────────────────────────────────
    {
        "title": "Goal-Line Technology — Ball Over",
        "incident_type": "goal_line",
        "correct_decision": "Goal Confirmed - Ball Fully Crossed Line",
        "rationale": "GLT confirmed whole of ball crossed whole of line by 3 cm before being cleared. Binary decision — goal stands.",
        "keywords": ["goal line technology", "GLT", "whole ball", "fully crossed", "cleared", "binary"],
        "tags": ["goal-line-tech", "ball-crossed", "goal-confirmed"],
        "match_context": {"teams": "England vs Germany", "competition": "World Cup", "year": 2010},
        "law_references": ["IFAB Law 10"],
        "outcome": "goal confirmed",
    },
    {
        "title": "No Goal — Ball Did Not Fully Cross",
        "incident_type": "goal_line",
        "correct_decision": "No Goal - Ball Not Fully Over Line",
        "rationale": "Keeper scooped ball back with small portion still on the line. Any part on or above line = not a goal.",
        "keywords": ["scooped back", "on the line", "not fully", "keeper saved", "no goal"],
        "tags": ["not-fully-over", "goal-denied", "keeper-scoop"],
        "match_context": {"teams": "Aston Villa vs Sheffield United", "competition": "Premier League", "year": 2020},
        "law_references": ["IFAB Law 10"],
        "outcome": "no goal",
    },

    # ── Other (2) ───────────────────────────────────────────
    {
        "title": "Mistaken Identity — Card Rescinded",
        "incident_type": "other",
        "correct_decision": "Card Reassigned to Correct Player",
        "rationale": "Referee booked wrong player amid a scuffle; VAR identified correct offender. Mistaken identity is one of the four VAR-reviewable categories.",
        "keywords": ["mistaken identity", "wrong player", "scuffle", "rescinded", "reassigned", "VAR review"],
        "tags": ["mistaken-identity", "rescinded", "VAR-intervention"],
        "match_context": {"teams": "Everton vs Leeds", "competition": "Premier League", "year": 2021},
        "law_references": ["VAR Protocol"],
        "outcome": "card reassigned",
    },
    {
        "title": "Clear and Obvious Threshold — On-Field Stands",
        "incident_type": "other",
        "correct_decision": "On-Field Decision Stands",
        "rationale": "Contact was marginal and evidence inconclusive. VAR threshold (clear and obvious error) not met — on-field referee's call must stand.",
        "keywords": ["clear and obvious", "threshold", "marginal", "inconclusive", "on-field stands", "check complete"],
        "tags": ["clear-and-obvious", "threshold-not-met", "on-field-stands"],
        "match_context": {"teams": "Inter vs Juventus", "competition": "Serie A", "year": 2023},
        "law_references": ["VAR Protocol"],
        "outcome": "on-field decision stands",
    },
]
