"""
OCTON VAR — 20 canonical VAR precedents.
Bootstraps the training corpus so the AI has binding precedent on day one.
Each case carries: title, incident_type, correct_decision, rationale, keywords,
tags, match_context, law_references, outcome.
"""
CANONICAL_CASES = [
    # ── Offside (4) ─────────────────────────────────────────
    {
        "title": "Armpit Offside - Sterling vs Villarreal",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside",
        "rationale": "Attacker's armpit was fractionally beyond the last defender at the moment the ball was played. Marginal but conclusive on semi-automated offside lines.",
        "keywords": ["semi-automated", "armpit", "marginal", "last defender", "through ball", "goal scored", "calibrated line"],
        "tags": ["marginal-offside", "semi-automated", "goal-disallowed"],
        "match_context": {"teams": "Man City vs Villarreal", "competition": "UEFA Champions League", "year": 2021},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal overturned",
    },
    {
        "title": "Played Onside by Defender - Alexander-Arnold",
        "incident_type": "offside",
        "correct_decision": "Onside - Goal Stands",
        "rationale": "Attacker appeared in an offside position but was played onside by a deliberate clearance from a defender. Deliberate play resets the offside phase.",
        "keywords": ["played onside", "deliberate clearance", "defender", "reset phase", "onside"],
        "tags": ["onside", "deliberate-play", "goal-stands"],
        "match_context": {"teams": "Liverpool vs Tottenham", "competition": "Premier League", "year": 2019},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal confirmed",
    },
    {
        "title": "Clear Daylight Offside - Set Piece Line",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside",
        "rationale": "Striker was more than a metre beyond the last defender when the ball was played. No interpretation needed — unambiguous call.",
        "keywords": ["daylight", "clear offside", "striker beyond", "metre beyond", "unambiguous"],
        "tags": ["clear-offside", "daylight", "goal-disallowed"],
        "match_context": {"teams": "Real Madrid vs Valencia", "competition": "La Liga", "year": 2022},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal overturned",
    },
    {
        "title": "Offside from Corner — Not Applicable",
        "incident_type": "offside",
        "correct_decision": "Onside - Goal Stands",
        "rationale": "There is no offside offence from a corner kick regardless of attacker position. On-field flag should be withdrawn.",
        "keywords": ["corner kick", "no offside", "not applicable", "header goal", "corner"],
        "tags": ["no-offside-rule", "corner", "goal-stands"],
        "match_context": {"teams": "Arsenal vs Chelsea", "competition": "Premier League", "year": 2020},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal confirmed",
    },

    # ── Handball (4) ────────────────────────────────────────
    {
        "title": "Arm Extended Away from Body - Goal Ruled Out",
        "incident_type": "handball",
        "correct_decision": "Handball - Goal Disallowed",
        "rationale": "Attacker's arm was clearly extended away from the body to intercept, making the body unnaturally bigger prior to scoring. Attacking-phase handball rule applies.",
        "keywords": ["arm extended", "body bigger", "attacking handball", "disallow goal", "unnatural"],
        "tags": ["arm-extended", "body-bigger", "attacking-handball", "goal-disallowed"],
        "match_context": {"teams": "France vs Tunisia", "competition": "World Cup", "year": 2022},
        "law_references": ["IFAB Law 12"],
        "outcome": "goal overturned",
    },
    {
        "title": "Ball-to-Hand from Close Range — No Handball",
        "incident_type": "handball",
        "correct_decision": "No Handball - Natural Position",
        "rationale": "Ball struck defender's arm from close range with the arm in a natural position by the side. No deliberate movement toward the ball.",
        "keywords": ["ball to hand", "close range", "natural position", "by the side", "deflection", "no handball"],
        "tags": ["ball-to-hand", "natural-position", "no-handball"],
        "match_context": {"teams": "Juventus vs Inter", "competition": "Serie A", "year": 2021},
        "law_references": ["IFAB Law 12"],
        "outcome": "play on",
    },
    {
        "title": "Handball in Box — Penalty",
        "incident_type": "handball",
        "correct_decision": "Penalty Awarded - Handball",
        "rationale": "Defender slid with arm fully extended outside body line to block the shot inside the penalty area. Clear handball offence, deliberate act of making body bigger.",
        "keywords": ["arm extended", "inside box", "blocked shot", "sliding", "body bigger", "penalty"],
        "tags": ["inside-box", "arm-extended", "blocked-shot", "penalty"],
        "match_context": {"teams": "Barcelona vs Sevilla", "competition": "La Liga", "year": 2023},
        "law_references": ["IFAB Law 12", "IFAB Law 14"],
        "outcome": "penalty awarded",
    },
    {
        "title": "Deflection off own Body to Arm — No Handball",
        "incident_type": "handball",
        "correct_decision": "No Handball - Own Body Deflection",
        "rationale": "Ball deflected off attacker's thigh onto his own arm immediately before scoring. Per 2021 IFAB amendment, only deliberate handball by scorer is penalised; accidental contact off own body is not.",
        "keywords": ["own body", "deflection", "thigh", "accidental", "scorer", "own arm"],
        "tags": ["own-body-deflection", "accidental", "goal-stands"],
        "match_context": {"teams": "Bayern vs Leipzig", "competition": "Bundesliga", "year": 2022},
        "law_references": ["IFAB Law 12"],
        "outcome": "goal confirmed",
    },

    # ── Foul / Penalty (4) ──────────────────────────────────
    {
        "title": "Tactical Foul Stopping Counter — Yellow Card",
        "incident_type": "foul",
        "correct_decision": "Yellow Card - Stopping Promising Attack",
        "rationale": "Defender committed a cynical trip near halfway line as attacker broke forward with numerical advantage. Stopping a promising attack = mandatory yellow.",
        "keywords": ["tactical foul", "counter-attack", "promising attack", "cynical", "yellow card", "trip", "halfway"],
        "tags": ["tactical-foul", "stopping-promising-attack", "yellow-card"],
        "match_context": {"teams": "Man Utd vs Liverpool", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "yellow card issued",
    },
    {
        "title": "Penalty - Trip Inside the Area",
        "incident_type": "penalty",
        "correct_decision": "Penalty Awarded",
        "rationale": "Defender made contact with attacker's trailing leg inside the penalty area with no prior touch on the ball. Clear trip, penalty and no card (not DOGSO).",
        "keywords": ["trip", "inside box", "penalty area", "trailing leg", "no ball contact", "penalty"],
        "tags": ["trip", "inside-box", "penalty", "no-card"],
        "match_context": {"teams": "PSG vs Marseille", "competition": "Ligue 1", "year": 2022},
        "law_references": ["IFAB Law 14"],
        "outcome": "penalty awarded",
    },
    {
        "title": "Simulation - Dive in Penalty Area",
        "incident_type": "penalty",
        "correct_decision": "No Penalty - Simulation, Yellow Card Attacker",
        "rationale": "Attacker initiated contact and went down theatrically with no meaningful defender contact. Simulation is sanctioned with a yellow card.",
        "keywords": ["dive", "simulation", "theatrical", "no contact", "initiated contact", "yellow card attacker"],
        "tags": ["simulation", "dive", "yellow-attacker", "no-penalty"],
        "match_context": {"teams": "Dortmund vs Leipzig", "competition": "Bundesliga", "year": 2021},
        "law_references": ["IFAB Law 14"],
        "outcome": "yellow to attacker",
    },
    {
        "title": "Holding Inside Box at Corner — Penalty",
        "incident_type": "penalty",
        "correct_decision": "Penalty Awarded - Shirt Pull",
        "rationale": "Defender grabbed attacker's shirt and pulled him to ground inside the area from a corner kick. Persistent holding offences in the box must be penalised.",
        "keywords": ["holding", "shirt pull", "corner kick", "inside box", "persistent", "grabbed shirt"],
        "tags": ["holding", "shirt-pull", "corner", "penalty"],
        "match_context": {"teams": "Atletico vs Real Madrid", "competition": "La Liga", "year": 2022},
        "law_references": ["IFAB Law 14"],
        "outcome": "penalty awarded",
    },

    # ── Red Card (4) ────────────────────────────────────────
    {
        "title": "Studs-Up Serious Foul Play — Red Card",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Serious Foul Play",
        "rationale": "Tackle made with studs up, at speed, above the ankle with excessive force — endangering the opponent's safety. Mandatory red card.",
        "keywords": ["studs up", "high boot", "excessive force", "endanger safety", "serious foul play", "red card"],
        "tags": ["studs-up", "serious-foul-play", "excessive-force", "red-card"],
        "match_context": {"teams": "Chelsea vs Arsenal", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "DOGSO — Professional Foul Outside Box",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Denying Obvious Goal-Scoring Opportunity",
        "rationale": "Last defender tripped attacker who was clean through on goal with no cover. DOGSO mandates red card (outside penalty area, no attempt to play ball).",
        "keywords": ["last defender", "DOGSO", "clear through", "professional foul", "no cover", "red card"],
        "tags": ["DOGSO", "last-defender", "red-card"],
        "match_context": {"teams": "Spurs vs Newcastle", "competition": "Premier League", "year": 2022},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "Violent Conduct Off the Ball — Red Card",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Violent Conduct",
        "rationale": "Player struck opponent with elbow off the ball in an aerial duel — deliberate, excessive force, not a genuine challenge. Violent conduct = red.",
        "keywords": ["elbow", "off the ball", "violent conduct", "aerial duel", "struck opponent", "deliberate"],
        "tags": ["violent-conduct", "elbow", "off-ball", "red-card"],
        "match_context": {"teams": "AC Milan vs Napoli", "competition": "Serie A", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "Reckless but Not Excessive — Yellow not Red",
        "incident_type": "red_card",
        "correct_decision": "Yellow Card - Reckless Challenge",
        "rationale": "Challenge was late and reckless but did not use excessive force or endanger safety. Yellow is appropriate; red would exceed the threshold.",
        "keywords": ["reckless", "late tackle", "not excessive", "yellow card", "not endangering"],
        "tags": ["reckless", "yellow-card", "not-serious-foul"],
        "match_context": {"teams": "Brentford vs Wolves", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "yellow card issued",
    },
    {
        "title": "Physical Contact With Referee — Automatic Violent Conduct",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Violent Conduct (Referee Contact)",
        "rationale": "Any deliberate physical contact with a match official (push, shove, grab, strike, headbutt, kick, spit) is automatic violent conduct under IFAB Law 12. No discretion, no 'clear and obvious' threshold — straight red card. Confidence must be very high whenever the description explicitly states the player made contact with the referee, assistant referee or 4th official.",
        "keywords": ["pushed referee", "shoved referee", "grabbed referee", "struck referee", "referee contact", "physical contact official", "angry player", "aggression toward referee", "howled referee", "contact with linesman", "violent conduct official"],
        "tags": ["violent-conduct", "referee-contact", "automatic-red", "no-discretion", "red-card"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12 (binding)", "year": 2024},
        "law_references": ["IFAB Law 12", "IFAB Law 5"],
        "outcome": "red card issued",
    },
    {
        "title": "Stamping on Opponent — Serious Foul Play Red",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Serious Foul Play (Stamping)",
        "rationale": "Player deliberately stamped on opponent's leg/ankle while ball was not in playable range. Stamping uses excessive force and endangers the opponent's safety — mandatory red.",
        "keywords": ["stamped on", "stamp", "stamping", "endangered safety", "ball not playable", "excessive force"],
        "tags": ["stamping", "serious-foul-play", "excessive-force", "red-card"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "Spitting at Opponent — Violent Conduct Red",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Violent Conduct (Spitting)",
        "rationale": "Spitting at any person (opponent, team-mate, match official, spectator) is automatic violent conduct under IFAB Law 12. Straight red card with no discretion.",
        "keywords": ["spat at", "spat on", "spit at", "spitting", "violent conduct", "automatic red"],
        "tags": ["spitting", "violent-conduct", "automatic-red", "red-card"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },

    # ── Goal Line (2) ───────────────────────────────────────
    {
        "title": "Goal-Line Technology — Ball Over",
        "incident_type": "goal_line",
        "correct_decision": "Goal Confirmed - Ball Fully Crossed Line",
        "rationale": "GLT confirmed whole of ball crossed whole of line by 3 cm before being cleared. Binary decision — goal stands.",
        "keywords": ["goal line technology", "GLT", "whole ball", "fully crossed", "cleared", "binary"],
        "tags": ["goal-line-tech", "ball-crossed", "goal-confirmed"],
        "match_context": {"teams": "England vs Germany", "competition": "World Cup", "year": 2010},
        "law_references": ["IFAB Law 10"],
        "outcome": "goal confirmed",
    },
    {
        "title": "No Goal — Ball Did Not Fully Cross",
        "incident_type": "goal_line",
        "correct_decision": "No Goal - Ball Not Fully Over Line",
        "rationale": "Keeper scooped ball back with small portion still on the line. Any part on or above line = not a goal.",
        "keywords": ["scooped back", "on the line", "not fully", "keeper saved", "no goal"],
        "tags": ["not-fully-over", "goal-denied", "keeper-scoop"],
        "match_context": {"teams": "Aston Villa vs Sheffield United", "competition": "Premier League", "year": 2020},
        "law_references": ["IFAB Law 10"],
        "outcome": "no goal",
    },

    # ── Other (2) ───────────────────────────────────────────
    {
        "title": "Mistaken Identity — Card Rescinded",
        "incident_type": "other",
        "correct_decision": "Card Reassigned to Correct Player",
        "rationale": "Referee booked wrong player amid a scuffle; VAR identified correct offender. Mistaken identity is one of the four VAR-reviewable categories.",
        "keywords": ["mistaken identity", "wrong player", "scuffle", "rescinded", "reassigned", "VAR review"],
        "tags": ["mistaken-identity", "rescinded", "VAR-intervention"],
        "match_context": {"teams": "Everton vs Leeds", "competition": "Premier League", "year": 2021},
        "law_references": ["VAR Protocol"],
        "outcome": "card reassigned",
    },
    {
        "title": "Clear and Obvious Threshold — On-Field Stands",
        "incident_type": "other",
        "correct_decision": "On-Field Decision Stands",
        "rationale": "Contact was marginal and evidence inconclusive. VAR threshold (clear and obvious error) not met — on-field referee's call must stand.",
        "keywords": ["clear and obvious", "threshold", "marginal", "inconclusive", "on-field stands", "check complete"],
        "tags": ["clear-and-obvious", "threshold-not-met", "on-field-stands"],
        "match_context": {"teams": "Inter vs Juventus", "competition": "Serie A", "year": 2023},
        "law_references": ["VAR Protocol"],
        "outcome": "on-field decision stands",
    },

    # ── Offside Interference Edge Cases (4) ─────────────────
    {
        "title": "Offside Interference — Blocking Goalkeeper's Line of Sight",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside Interference (Law 11)",
        "rationale": "Attacker in offside position stood directly in goalkeeper's line of sight as the shot was struck. Even without touching the ball, blocking the keeper's vision constitutes interference with an opponent under Law 11. Goal must be disallowed.",
        "keywords": ["offside interference", "line of sight", "blocked vision", "obstructed keeper", "passive offside became active", "shot from distance", "no touch but interfered"],
        "tags": ["offside-interference", "blocked-keeper-vision", "law-11", "goal-disallowed"],
        "match_context": {"teams": "Tottenham vs Leeds", "competition": "Premier League", "year": 2021},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal overturned",
    },
    {
        "title": "Offside Rebound from Goalkeeper Save — Goal Disallowed",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside (Rebound from Save)",
        "rationale": "Striker was in offside position when team-mate's shot was struck. Goalkeeper saved the shot and ball rebounded to the offside attacker who scored. A save does NOT reset the offside phase — only a deliberate play (not a save) by a defender resets it. Goal must be disallowed.",
        "keywords": ["rebound from save", "keeper save", "offside rebound", "save does not reset", "deliberate save", "no reset phase", "offside attacker scored"],
        "tags": ["rebound-offside", "save-no-reset", "law-11", "goal-disallowed"],
        "match_context": {"teams": "Bayern vs Dortmund", "competition": "Bundesliga", "year": 2022},
        "law_references": ["IFAB Law 11", "IFAB 2022 Deliberate Play Clarification"],
        "outcome": "goal overturned",
    },
    {
        "title": "Offside Reset by Deliberate Defensive Play (2022 Clarification)",
        "incident_type": "offside",
        "correct_decision": "Onside - Goal Stands (Deliberate Play Reset)",
        "rationale": "Defender saw the ball coming, was in control, had time and space, and deliberately played it (controlled clearance under no immediate pressure). Per IFAB 2022 clarification, a deliberate defensive play resets the offside phase — the previously offside attacker is now onside. Goal stands.",
        "keywords": ["deliberate play", "controlled clearance", "defender in control", "had time and space", "reset phase", "2022 clarification", "deliberate defensive"],
        "tags": ["deliberate-play-reset", "onside-after-reset", "law-11", "2022-clarification", "goal-stands"],
        "match_context": {"teams": "Newcastle vs Arsenal", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 11", "IFAB 2022 Deliberate Play Clarification"],
        "outcome": "goal confirmed",
    },
    {
        "title": "Offside Challenge for Ball — Active Interference",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside Interference (Challenge)",
        "rationale": "Offside-position attacker actively challenged a defender for a header on the goal-bound cross. Even though team-mate scored, the offside attacker's challenge for the ball constitutes interfering with an opponent. Active interference, goal disallowed.",
        "keywords": ["offside challenge", "competed for ball", "interfering with opponent", "challenged defender", "active offside", "header goal disallowed"],
        "tags": ["active-interference", "challenged-for-ball", "law-11", "goal-disallowed"],
        "match_context": {"teams": "Liverpool vs Aston Villa", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal overturned",
    },

    # ── DOGSO vs SPA Distinction (3) ────────────────────────
    {
        "title": "DOGSO Inside Box — Genuine Attempt to Play Ball (Yellow only)",
        "incident_type": "red_card",
        "correct_decision": "Yellow Card + Penalty (DOGSO Triple-Punishment Exception)",
        "rationale": "Defender committed foul inside the penalty area while making a genuine attempt to play the ball, denying an obvious goal-scoring opportunity. Per 2017 IFAB amendment, DOGSO inside the box becomes a yellow card (not red) when the foul is a genuine attempt to play the ball. Avoids 'triple punishment' (penalty + red + suspension). Penalty awarded, yellow card only.",
        "keywords": ["DOGSO in box", "genuine attempt", "trying to play ball", "triple punishment", "yellow not red", "2017 amendment", "downgraded card", "DOGSO exception"],
        "tags": ["DOGSO-inside-box", "genuine-attempt", "triple-punishment-rule", "yellow-card", "2017-amendment"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12 (binding)", "year": 2017},
        "law_references": ["IFAB Law 12", "IFAB 2017 DOGSO Amendment"],
        "outcome": "yellow card + penalty",
    },
    {
        "title": "DOGSO Inside Box — Holding/Pulling (Red Card)",
        "incident_type": "red_card",
        "correct_decision": "Red Card - DOGSO (Holding) + Penalty",
        "rationale": "Defender denied an obvious goal-scoring opportunity by holding/pulling the attacker's shirt inside the penalty area — NOT a genuine attempt to play the ball. The 2017 'genuine attempt' exception does NOT apply to holding, pushing, or shirt-pulling offences. Full DOGSO red card stands plus penalty.",
        "keywords": ["DOGSO holding", "shirt pull", "no genuine attempt", "not playing ball", "DOGSO red", "holding offence", "DOGSO standard"],
        "tags": ["DOGSO-inside-box", "no-genuine-attempt", "holding", "red-card", "penalty"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12", "IFAB 2017 DOGSO Amendment"],
        "outcome": "red card + penalty",
    },
    {
        "title": "SPA Outside Box — Yellow Card Only",
        "incident_type": "foul",
        "correct_decision": "Yellow Card - Stopping a Promising Attack (SPA)",
        "rationale": "Foul stopped a promising attack outside the penalty area but the attacker was not clean through (cover defender present, distance from goal, ball not under control). DOGSO criteria (4-point checklist) NOT met — only SPA. Yellow card, not red.",
        "keywords": ["SPA", "stopping promising attack", "not DOGSO", "cover defender", "yellow card", "outside box", "no clean through"],
        "tags": ["SPA", "not-DOGSO", "yellow-card", "cover-defender"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "yellow card issued",
    },

    # ── Handball Edge Cases (3) ─────────────────────────────
    {
        "title": "Handball Justifiable Position — Sliding Tackle (No Offence)",
        "incident_type": "handball",
        "correct_decision": "No Handball - Arm Supporting Body (Justifiable)",
        "rationale": "Defender's arm was on the ground supporting body weight during a sliding tackle when the ball struck it. Per IFAB Law 12, when a player's arm is in a position to support the body (e.g. when sliding, falling, or jumping for a header), it is NOT considered to have 'made the body unnaturally bigger'. No offence, play on.",
        "keywords": ["arm supporting body", "sliding tackle", "justifiable position", "supporting weight", "natural for action", "no handball offence", "body support"],
        "tags": ["arm-supporting-body", "justifiable-position", "natural-for-action", "no-handball"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "play on",
    },
    {
        "title": "Accidental Handball Leading to Team-mate Goal (No Offence — 2021+)",
        "incident_type": "handball",
        "correct_decision": "Goal Stands - Only Scorer's Deliberate Handball Counts (2021)",
        "rationale": "Ball deflected accidentally off attacker A's arm, then attacker B (different player, not the scorer) scored. Per 2021 IFAB amendment, only the scorer's own handball offence (or an immediately-preceding deliberate handball by the scorer) negates the goal. Accidental handball by a TEAM-MATE leading to a goal is no longer an offence. Goal stands.",
        "keywords": ["accidental handball team-mate", "different scorer", "2021 amendment", "deflection chain", "goal stands handball", "non-scorer accidental"],
        "tags": ["2021-amendment", "team-mate-handball", "non-scorer", "goal-stands"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12 (2021)", "year": 2021},
        "law_references": ["IFAB Law 12", "IFAB 2021 Handball Amendment"],
        "outcome": "goal confirmed",
    },
    {
        "title": "Goalkeeper Handling Outside Penalty Area — Indirect/Direct Free Kick",
        "incident_type": "handball",
        "correct_decision": "Direct Free Kick + Yellow Card (Goalkeeper Handled Outside PA)",
        "rationale": "Goalkeeper picked up / parried the ball outside their own penalty area. Per Law 12, goalkeepers may only handle inside their own PA. Outside PA = direct free kick offence; if it denies a promising attack or DOGSO, additional sanctions apply (YC for SPA, RC for DOGSO).",
        "keywords": ["keeper outside box", "goalkeeper handled outside area", "rushed out", "direct free kick", "keeper handball", "outside PA"],
        "tags": ["keeper-outside-PA", "direct-free-kick", "keeper-handball", "law-12"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "direct free kick",
    },

    # ── Penalty / Encroachment 2024 (2) ─────────────────────
    {
        "title": "Penalty Encroachment by Attacker — Retake / Indirect Free Kick (2024)",
        "incident_type": "penalty",
        "correct_decision": "Penalty Retaken (if missed) / Indirect FK to Defending Team (if scored)",
        "rationale": "Attacking team-mate encroached significantly into the penalty area before the kick was struck and was first to play the rebound after a save. Per 2024 IFAB amendment: if the encroaching attacker scores or plays the rebound first, the kick is retaken (or, on a successful kick, the goal is disallowed and an indirect free kick is awarded against the attacking team).",
        "keywords": ["encroachment attacker", "penalty retake", "encroached into box", "first to rebound", "2024 amendment", "indirect free kick", "penalty encroachment"],
        "tags": ["penalty-encroachment", "attacker-encroached", "retake", "2024-amendment"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 14 (2024)", "year": 2024},
        "law_references": ["IFAB Law 14", "IFAB 2024 Encroachment Update"],
        "outcome": "penalty retaken",
    },
    {
        "title": "Penalty Encroachment by Defender — Retake (if missed)",
        "incident_type": "penalty",
        "correct_decision": "Penalty Retaken (if missed) / Goal Stands (if scored)",
        "rationale": "Defending team-mate encroached into the penalty area before the kick. If the penalty is missed or saved, the kick is retaken. If the penalty is scored, the goal stands (no retake to the defender's advantage). Per IFAB Law 14.",
        "keywords": ["defender encroachment", "encroached defender", "penalty retake missed", "goal stands scored", "law 14", "defender into box"],
        "tags": ["penalty-encroachment", "defender-encroached", "retake-if-missed", "law-14"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 14", "year": 2024},
        "law_references": ["IFAB Law 14"],
        "outcome": "retake or goal stands",
    },

    # ── Second Yellow / Cumulative Cautions (1) ─────────────
    {
        "title": "Second Caution = Sending Off (Two Yellows)",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Two Cautions in Same Match (Second Yellow)",
        "rationale": "Player committed a second cautionable offence after already receiving a yellow card earlier in the same match. Two cautions in the same match result in a sending-off (red card) per IFAB Law 12. Note: this is a 'second yellow red' which carries a one-match suspension (lighter than a straight red).",
        "keywords": ["second yellow", "two cautions", "two yellows", "second booking", "cumulative caution", "sending off two yellows", "second yellow red"],
        "tags": ["second-yellow", "two-cautions", "red-card", "law-12"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued (second yellow)",
    },

    # ── Foul / Reckless vs SFP threshold (1) ────────────────
    {
        "title": "Hard Tackle With Some Reckless Elements — Yellow (Threshold not crossed)",
        "incident_type": "foul",
        "correct_decision": "Yellow Card - Reckless Challenge (No SFP)",
        "rationale": "Player went into challenge firmly with some recklessness (slightly late, raised foot a fraction) but did NOT use excessive force, did NOT endanger the opponent's safety, and ball was within playable range. Crosses the 'reckless' line (yellow) but not the 'excessive force / endangers safety' line that would make it Serious Foul Play (red). Yellow only.",
        "keywords": ["hard tackle", "slight reckless", "not excessive force", "did not endanger", "ball in range", "yellow not red", "borderline yellow", "sfp threshold"],
        "tags": ["reckless", "yellow-card", "not-SFP", "threshold-borderline"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "yellow card issued",
    },
    # ── Corner Kick — IFAB Law 17 (4) ───────────────────────
    {
        "title": "Last Touch Defender — Legal Corner Awarded",
        "incident_type": "corner",
        "correct_decision": "Legal Corner Kick — Last Touch Defender",
        "rationale": "The whole of the ball crossed the goal line (on the ground) having last been touched by the defending centre-back as he tried to clear. Corner kick is the correct restart. IFAB Law 17.",
        "keywords": ["last touch defender", "deflection", "crossed byline", "whole ball over line", "corner awarded", "legal corner"],
        "tags": ["law-17", "legal-corner", "award-direction"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 17", "year": 2024},
        "law_references": ["IFAB Law 17"],
        "outcome": "corner kick awarded",
    },
    {
        "title": "Attacker's Own Shot Wide — Goal Kick, Not Corner",
        "incident_type": "corner",
        "correct_decision": "Goal Kick — Last Touch Attacker",
        "rationale": "Striker's shot deflected only very slightly off the defender's thigh before leaving the byline — forensic review of 4 angles confirms the ball's final meaningful touch was the attacking shot. The defender's deflection was incidental; restart is a goal kick, not a corner. Award-direction error was clear and obvious.",
        "keywords": ["shot went wide", "last touch attacker", "incidental deflection", "goal kick not corner", "award direction error"],
        "tags": ["law-17", "goal-kick", "award-overturned"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 17", "year": 2024},
        "law_references": ["IFAB Law 17"],
        "outcome": "corner overturned to goal kick",
    },
    {
        "title": "Defender Blocking Goalkeeper at Delivery — Retake & Foul",
        "incident_type": "corner",
        "correct_decision": "Retake — Defensive Infringement at Delivery",
        "rationale": "Two defenders deliberately screened the goalkeeper inside the 6-yard box at the exact moment the corner was delivered, preventing him from attempting to claim the cross. This is an infringement of Law 12 (impeding an opponent) at the instant the ball enters play. Because the blocking directly influenced the passage of play, the correct restart is a retake; repeated offenders are cautioned.",
        "keywords": ["goalkeeper blocked", "screen on keeper", "holding the keeper", "retake corner", "defensive infringement"],
        "tags": ["law-17", "retake", "defensive-foul", "keeper-impeded"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 17 + Law 12", "year": 2024},
        "law_references": ["IFAB Law 17", "IFAB Law 12"],
        "outcome": "corner retaken + yellow card",
    },
    {
        "title": "Encroachment Inside 1m Arc — Retake Required",
        "incident_type": "corner",
        "correct_decision": "Retake — Encroachment Inside 1m",
        "rationale": "Defending midfielder stood inside the mandatory 1-metre distance from the corner arc at the moment the kick was taken and actively obstructed the kicker's delivery. Law 17 mandates opponents remain at least 1m from the arc until the ball is in play — violation influencing play = retake.",
        "keywords": ["encroachment", "inside 1m", "corner arc", "retake", "obstructed delivery"],
        "tags": ["law-17", "encroachment", "retake"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 17", "year": 2024},
        "law_references": ["IFAB Law 17"],
        "outcome": "corner retaken",
    },
    # ────────── EXPANSION 2026-02: 40 additional precedents ──────────
    # Bringing corpus to 81 canonical cases so similarity retrieval has
    # a dense, high-agreement set to boost every verdict's confidence.
    #
    # ── FOULS IN FRONT OF GOAL (DOGSO/SPA) — 10 cases ──
    {
        "title": "DOGSO Yellow + Penalty — Defender mistimed slide in box but got ball first-touch",
        "incident_type": "foul",
        "correct_decision": "Yellow Card + Penalty Kick (DOGSO, genuine attempt to play ball)",
        "rationale": "Defender slid in a one-on-one situation inside the penalty area and clipped the attacker's trailing leg after clearly touching the ball. Genuine attempt to play the ball established — double-jeopardy relief (IFAB 2016/17) mandates Yellow + PK rather than Red + PK. All 4 D's of DOGSO satisfied (distance ≤ 18m, direction to goal, only GK to beat, high difficulty).",
        "keywords": ["DOGSO", "double jeopardy", "slid for ball", "genuine attempt", "penalty yellow card", "one on one"],
        "tags": ["law-12", "DOGSO", "double-jeopardy-relief"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12 §1", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "Yellow + Penalty",
    },
    {
        "title": "DOGSO Red + Penalty — Shirt-pull on striker inside box (no ball attempt)",
        "incident_type": "foul",
        "correct_decision": "Red Card + Penalty Kick (DOGSO, holding, no attempt at ball)",
        "rationale": "Centre-back held the striker's shirt from behind at full sprint towards the keeper inside the penalty area. No attempt to play the ball — classic holding offence under Law 12. All 4 D's of DOGSO met. Full sanction applies (no double-jeopardy relief because there was no attempt at the ball).",
        "keywords": ["DOGSO", "shirt pull", "holding", "penalty red card", "no attempt"],
        "tags": ["law-12", "DOGSO", "holding-no-attempt"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12 §1", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "Red + Penalty",
    },
    {
        "title": "DOGSO Outside Box — Free kick + Red card",
        "incident_type": "foul",
        "correct_decision": "Red Card + Direct Free Kick",
        "rationale": "Last defender tripped the through-running attacker 25m from goal after the attacker had beaten him for pace. No defender between attacker and goalkeeper. Distance/Direction/Defenders/Difficulty all satisfied. Because offence is OUTSIDE the penalty area, the 2016 double-jeopardy relief does not apply — full DOGSO sanction: sending off + direct FK.",
        "keywords": ["DOGSO outside box", "last defender", "red card", "through ball trip"],
        "tags": ["law-12", "DOGSO", "outside-box"],
        "match_context": {"teams": "Champions League Universal", "competition": "IFAB Law 12 §1", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "Red + Direct FK",
    },
    {
        "title": "SPA inside box, genuine attempt — Penalty only (no card)",
        "incident_type": "foul",
        "correct_decision": "Penalty Kick — no card (SPA + genuine attempt)",
        "rationale": "Defender clipped attacker after a legitimate slide attempt inside the box. Goal-scoring chance was PROMISING (not obvious — two defenders behind). Stops-a-Promising-Attack classification + genuine attempt on the ball = no card, penalty only. This is the SPA/genuine-attempt row of the 9-row sanction table.",
        "keywords": ["SPA", "stopping promising attack", "penalty no card", "genuine attempt"],
        "tags": ["law-12", "SPA", "no-card"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12 §1", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "Penalty only",
    },
    {
        "title": "Serious Foul Play — two-footed lunge, studs up",
        "incident_type": "foul",
        "correct_decision": "Red Card — Serious Foul Play",
        "rationale": "Midfielder launched two-footed, studs-showing, at shin-height with full body weight. Endangering opponent safety (Law 12 excessive force test). Straight red regardless of location on the pitch and regardless of whether he won the ball — the manner of the challenge itself is the offence.",
        "keywords": ["two-footed", "studs up", "serious foul play", "red card", "endangering safety"],
        "tags": ["law-12", "serious-foul-play", "excessive-force"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "Red card direct",
    },
    {
        "title": "Violent Conduct — off-the-ball elbow to face",
        "incident_type": "foul",
        "correct_decision": "Red Card — Violent Conduct",
        "rationale": "Defender deliberately led with his elbow into the attacker's face away from the ball, during a set-piece scrum. Violent Conduct (Law 12) carries an automatic red. VAR is empowered to intervene even on missed incidents of this severity.",
        "keywords": ["violent conduct", "elbow face", "off the ball", "red card"],
        "tags": ["law-12", "violent-conduct", "off-the-ball"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "Red card direct",
    },
    {
        "title": "Reckless Challenge — Yellow card (Law 12 careless/reckless test)",
        "incident_type": "foul",
        "correct_decision": "Yellow Card — Reckless foul",
        "rationale": "Midfielder slid in at high speed with excessive disregard for opponent safety but without endangering opponent safety. 'Reckless' is the middle band of Law 12's three-tier test (careless / reckless / excessive force) and mandates a caution.",
        "keywords": ["reckless challenge", "yellow card", "careless reckless"],
        "tags": ["law-12", "reckless", "yellow-card"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "Yellow card",
    },
    {
        "title": "Simulation in Box — Yellow card, IFK, NO penalty",
        "incident_type": "foul",
        "correct_decision": "Yellow card + Indirect Free Kick to defending team (Simulation)",
        "rationale": "Attacker threw himself to the ground in the penalty area with no contact from the defender. Clear act of simulation/deception. 2025/26 update: mandatory caution, NO advantage or replay available, defending team restarts with an indirect free kick. No penalty.",
        "keywords": ["simulation", "dive", "yellow card", "no penalty", "indirect free kick"],
        "tags": ["law-12", "simulation", "2025-26"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12.3 (2025/26)", "year": 2025},
        "law_references": ["IFAB Law 12"],
        "outcome": "Yellow + IFK to defending team",
    },
    {
        "title": "DOGSO + Advantage → Goal scored — caution waived (2025/26)",
        "incident_type": "foul",
        "correct_decision": "Goal stands, no card (DOGSO caution-on-advantage waiver)",
        "rationale": "Referee played advantage on a DOGSO foul; attacker recovered, advanced and scored. 2025/26 IFAB update: when advantage is played on a DOGSO foul AND the team scores, the caution/red for DOGSO is no longer issued. Just the goal stands. If advantage had failed (no goal), original DOGSO sanction would have applied.",
        "keywords": ["DOGSO advantage", "goal scored advantage", "no card 2025-26", "caution waiver"],
        "tags": ["law-12", "DOGSO", "advantage", "2025-26"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12 (2025/26)", "year": 2025},
        "law_references": ["IFAB Law 12"],
        "outcome": "Goal stands, no card",
    },
    {
        "title": "Foul on goalkeeper controlling the ball — IFK to defending team",
        "incident_type": "foul",
        "correct_decision": "Indirect Free Kick to defending team (attacker charged GK in control)",
        "rationale": "Attacker clattered into the goalkeeper while the keeper was in clear control of the ball (both hands on it). Law 12.2 mandates an indirect free kick to the defending team whenever an attacker fouls a goalkeeper in control or about to release the ball. No card unless contact was reckless.",
        "keywords": ["foul on keeper", "charging keeper", "IFK to defenders", "keeper in control"],
        "tags": ["law-12", "goalkeeper-protection"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12.2", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "IFK to defending team",
    },

    # ── OFFSIDE variations — 8 cases ──
    {
        "title": "Offside — attacker in line with second-last defender is ONSIDE",
        "incident_type": "offside",
        "correct_decision": "Onside — Goal stands (line = onside per Law 11)",
        "rationale": "At the moment of pass, attacker's leading body part was LEVEL with second-last defender's trailing body part — even a fraction of a centimetre behind or level counts as onside under Law 11. 'Even is on.' SAOT-era clarification preserved.",
        "keywords": ["offside level", "even is on", "onside", "second last defender line"],
        "tags": ["law-11", "offside", "onside-line"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 11", "year": 2024},
        "law_references": ["IFAB Law 11"],
        "outcome": "Goal stands",
    },
    {
        "title": "Offside — daylight offside, clear sight line",
        "incident_type": "offside",
        "correct_decision": "Offside — goal disallowed (clear daylight)",
        "rationale": "At the moment of pass the attacker's forward shoulder was ~40 cm beyond the second-last defender's hip. No semi-automated data needed — naked-eye daylight visible. Goal disallowed per Law 11 offside offences (interfering with play by receiving the ball).",
        "keywords": ["daylight offside", "clear offside", "goal disallowed", "interfering with play"],
        "tags": ["law-11", "offside", "daylight"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 11", "year": 2024},
        "law_references": ["IFAB Law 11"],
        "outcome": "Offside - Goal disallowed",
    },
    {
        "title": "Offside — attacker deflects own team's shot while in offside position",
        "incident_type": "offside",
        "correct_decision": "Offside — interfering with play (deflection)",
        "rationale": "Attacker, in an offside position at the moment the shot was struck, deflected the ball into goal. Law 11 offence: 'interfering with play by touching or playing a ball passed or touched by a teammate'. Goal disallowed.",
        "keywords": ["offside deflection", "played ball", "interfering with play", "offside position"],
        "tags": ["law-11", "offside", "deflection"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 11", "year": 2024},
        "law_references": ["IFAB Law 11"],
        "outcome": "Offside - Goal disallowed",
    },
    {
        "title": "Offside — armpit offside (2021 armpit rule)",
        "incident_type": "offside",
        "correct_decision": "Offside — attacker's armpit/shoulder ahead",
        "rationale": "Attacker's armpit/top of shoulder was marginally ahead of second-last defender at moment of pass. Under Law 11 (post-2021 clarification), any body part that can score counts for offside — so shoulders and upper arm to armpit counts. Hands/arms (below armpit) do NOT count. Offside stands.",
        "keywords": ["armpit offside", "shoulder offside", "2021 offside clarification", "semi-automated"],
        "tags": ["law-11", "offside", "armpit-rule"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 11 (2021+)", "year": 2022},
        "law_references": ["IFAB Law 11"],
        "outcome": "Offside - Goal disallowed",
    },
    {
        "title": "Offside from GK throw — line judged at moment of hand-release (2025/26)",
        "incident_type": "offside",
        "correct_decision": "Offside line at last hand-contact of goalkeeper throw",
        "rationale": "2025/26 IFAB clarification: for an offside offence from a GOALKEEPER THROW, the offside line is judged at the LAST POINT OF CONTACT between the goalkeeper's hand and the ball — not at any later release point. This tightens what used to be ambiguous.",
        "keywords": ["goalkeeper throw", "offside from throw", "2025-26", "last hand contact"],
        "tags": ["law-11", "offside", "2025-26", "gk-throw"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 11 (2025/26)", "year": 2025},
        "law_references": ["IFAB Law 11"],
        "outcome": "Offside at release",
    },
    {
        "title": "Offside phase — attacker active, SAOT confirms marginal offside",
        "incident_type": "offside",
        "correct_decision": "Offside — SAOT confirms (marginal)",
        "rationale": "Semi-Automated Offside Technology (SAOT) confirmed attacker's forward knee was 4 cm beyond the second-last defender at moment of pass. Under current SAOT-era protocol, marginal SAOT offsides are binding — the 12-second average check ensures no inspection gap. Goal disallowed.",
        "keywords": ["SAOT", "semi-automated offside", "marginal offside", "technology confirmed"],
        "tags": ["law-11", "offside", "SAOT"],
        "match_context": {"teams": "UEFA Champions League Universal", "competition": "IFAB Law 11 (SAOT)", "year": 2024},
        "law_references": ["IFAB Law 11"],
        "outcome": "Offside - Goal disallowed (SAOT)",
    },
    {
        "title": "Offside phase — active but not interfering with play / opponent",
        "incident_type": "offside",
        "correct_decision": "Onside — no offside offence (no interference)",
        "rationale": "Attacker was in an offside position but (1) did not touch the ball, (2) did not challenge an opponent for it, and (3) was not in the line of sight of a defender making a save. Law 11 requires an actual OFFENCE (interfering / gaining advantage / impeding), not merely being offside. Play continues, goal stands.",
        "keywords": ["offside position", "not interfering", "no offence", "play continues"],
        "tags": ["law-11", "offside", "no-offence"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 11", "year": 2024},
        "law_references": ["IFAB Law 11"],
        "outcome": "Goal stands",
    },
    {
        "title": "Offside — deflected by defender does not reset (deliberate-save nuance)",
        "incident_type": "offside",
        "correct_decision": "Offside — attacker played from previously-offside position",
        "rationale": "Attacker in offside position ran onto a ball that a defender had saved/blocked (not a deliberate play). A deliberate 'save' or 'block' does NOT reset offside — only a deliberate PLAY (controlled kick/header to pass) does. Because defender was blocking a shot, the attacker remained offside when receiving the rebound.",
        "keywords": ["deliberate save", "deliberate play", "offside reset", "block rebound"],
        "tags": ["law-11", "offside", "deliberate-save"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 11 (2019 amendment)", "year": 2021},
        "law_references": ["IFAB Law 11"],
        "outcome": "Offside - Goal disallowed",
    },

    # ── HANDBALL variations — 8 cases ──
    {
        "title": "Handball — arm extended away from body, blocking shot (APP)",
        "incident_type": "handball",
        "correct_decision": "Penalty Kick (handball, unnaturally bigger)",
        "rationale": "Defender extended his arm to the side, away from his body, to block an opponent's shot inside the penalty area. 'Makes his body unnaturally bigger' test (Law 12.1) satisfied — penalty awarded. No card (unless the shot was goal-bound AND this was DOGSO by handball, which would add a red).",
        "keywords": ["handball unnaturally bigger", "arm extended", "block shot", "APP penalty"],
        "tags": ["law-12", "handball", "APP"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12.1 (2021)", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "Penalty",
    },
    {
        "title": "Handball — deliberate handball in box + DOGSO (red + pen)",
        "incident_type": "handball",
        "correct_decision": "Red Card + Penalty (deliberate handball denying goal)",
        "rationale": "Defender deliberately raised his arm to a goal-bound shot inside the penalty area. Deliberate handball denying a goal = Red card (DOGSO by handball) + penalty. Double jeopardy does NOT apply because the offence was deliberate (not a natural arm position).",
        "keywords": ["deliberate handball", "DOGSO handball", "red card penalty", "denying goal"],
        "tags": ["law-12", "handball", "DOGSO"],
        "match_context": {"teams": "Champions League Universal", "competition": "IFAB Law 12 + Law 12.1", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "Red + Penalty",
    },
    {
        "title": "Handball — ball strikes hand tucked into body (no offence)",
        "incident_type": "handball",
        "correct_decision": "No offence — arm in natural position",
        "rationale": "Ball deflected off an opponent's knee and struck the defender's arm which was tucked tight to the torso in a natural running position. 2021 Law 12.1 narrowing: only handball if arm in unnatural position OR above the shoulder OR deliberate. No offence — play on.",
        "keywords": ["natural arm position", "no handball", "deflection hand", "arm tucked"],
        "tags": ["law-12", "handball", "natural-position"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12.1 (2021 narrowing)", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "Play on",
    },
    {
        "title": "Handball — attacker scoring after own handball in build-up (only scorer)",
        "incident_type": "handball",
        "correct_decision": "Goal disallowed — attacker handball in build-up",
        "rationale": "Attacker controlled the ball with his arm/hand two touches before finishing. 2021 narrowing: goal is disallowed only when the SCORER handles. Teammate handballs earlier in the phase no longer auto-disallow. Here the SCORER handled two touches before the finish = disallowed.",
        "keywords": ["attacker handball", "build up handball", "goal disallowed", "scorer handball"],
        "tags": ["law-12", "handball", "attacker-handball"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12.1 (2021 narrowing)", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "Goal disallowed",
    },
    {
        "title": "Handball — accidental ricochet off teammate's arm before goal (goal stands)",
        "incident_type": "handball",
        "correct_decision": "Goal stands — teammate handball not penalised (2021)",
        "rationale": "Ball ricocheted accidentally off a teammate's arm 3 touches earlier in the move before the goal was scored. 2021 IFAB narrowing: teammate handballs in build-up NO LONGER cause automatic disallow — only scorer's handball does. Goal stands.",
        "keywords": ["teammate handball", "accidental handball", "2021 narrowing", "goal stands"],
        "tags": ["law-12", "handball", "2021-narrowing"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12.1 (2021 narrowing)", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "Goal stands",
    },
    {
        "title": "Handball — arm above shoulder blocking cross is unnatural",
        "incident_type": "handball",
        "correct_decision": "Penalty — arm above shoulder",
        "rationale": "Defender jumped with arm raised ABOVE shoulder height to block a cross inside the box. Law 12.1: arm above shoulder is categorically unnatural. Penalty awarded. No card unless the ball was goal-bound and this was DOGSO (+red).",
        "keywords": ["arm above shoulder", "handball penalty", "jumping handball"],
        "tags": ["law-12", "handball", "above-shoulder"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12.1 (2021)", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "Penalty",
    },
    {
        "title": "Handball in box — attacker's arm accidentally touches ball before assist",
        "incident_type": "handball",
        "correct_decision": "Goal stands — only scorer's handball in immediate build-up counts",
        "rationale": "The assisting attacker's arm made accidental contact with the ball, then he passed to the scorer who finished from 12 yards. Because the SCORER did not handle and the assister's touch was 2+ touches earlier, 2021 IFAB narrowing applies — goal stands.",
        "keywords": ["attacker handball assist", "two touches before", "2021 narrowing", "goal stands"],
        "tags": ["law-12", "handball", "2021-narrowing", "build-up"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12.1 (2021 narrowing)", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "Goal stands",
    },
    {
        "title": "Handball — holding in box + handball = red + penalty",
        "incident_type": "handball",
        "correct_decision": "Red + Penalty — holding offence combined with handball",
        "rationale": "Defender held the attacker's shirt AND blocked a shot with an extended arm inside the penalty area. 2025/26 clarification allows VAR to intervene for penalty-area holding denying a clear goal-scoring chance. Combined with the handball offence, sanction is red card + penalty.",
        "keywords": ["holding and handball", "red penalty 2025-26", "VAR intervention holding"],
        "tags": ["law-12", "handball", "holding", "2025-26"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12 (2025/26)", "year": 2025},
        "law_references": ["IFAB Law 12"],
        "outcome": "Red + Penalty",
    },

    # ── PENALTY variants — 4 cases ──
    {
        "title": "Penalty — accidental double-touch scored (retake per 2025/26)",
        "incident_type": "penalty",
        "correct_decision": "Retake — Accidental Double-Touch (2025/26)",
        "rationale": "Penalty kicker slipped while striking the ball; the ball bounced off his standing foot (inadvertent double-touch) and rolled in for a goal. 2025/26 IFAB clarification: when the double-touch is accidental and the kick is SCORED, the goal is disallowed and the kick is RETAKEN (not an indirect free-kick, because the double-touch was unintentional). Deliberate double-touch would still yield an IFK to defenders.",
        "keywords": ["penalty double-touch", "retake penalty", "accidental slip", "2025-26"],
        "tags": ["law-14", "penalty", "double-touch", "2025-26"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 14 (2025/26)", "year": 2025},
        "law_references": ["IFAB Law 14"],
        "outcome": "Penalty retaken",
    },
    {
        "title": "Penalty — goalkeeper encroachment before kick taken",
        "incident_type": "penalty",
        "correct_decision": "Retake if saved, Goal stands if scored (GK encroachment)",
        "rationale": "Goalkeeper had both feet clearly off the goal-line at the moment the kicker made contact with the ball. Law 14: if saved, penalty is retaken AND keeper cautioned. If scored, goal stands. VAR checks all penalties for this.",
        "keywords": ["GK encroachment", "penalty retake", "goal line off", "Law 14"],
        "tags": ["law-14", "penalty", "GK-encroachment"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 14", "year": 2024},
        "law_references": ["IFAB Law 14"],
        "outcome": "Retake if saved",
    },
    {
        "title": "Penalty — encroachment by attacker who does not score",
        "incident_type": "penalty",
        "correct_decision": "Indirect free kick to defending team (attacker encroachment, not scored)",
        "rationale": "Attacker from the kicker's team encroached into the penalty area before the kick was taken. The kick was saved. Because the encroacher was from the ATTACKING team and the kick was NOT scored, the restart is an indirect free kick to the defending team (Law 14).",
        "keywords": ["attacker encroachment", "penalty IFK", "not scored", "Law 14 encroachment"],
        "tags": ["law-14", "penalty", "encroachment"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 14", "year": 2024},
        "law_references": ["IFAB Law 14"],
        "outcome": "IFK to defending team",
    },
    {
        "title": "Penalty — foul by defender JUST outside box (DFK, no pen)",
        "incident_type": "penalty",
        "correct_decision": "Direct Free Kick (foul outside area)",
        "rationale": "Defender fouled attacker 2 yards outside the penalty area. VAR confirmed point of contact was outside the line. Restart = direct free kick from the point of contact; no penalty. If the foul also constitutes DOGSO, red card applies additionally.",
        "keywords": ["foul outside box", "not penalty", "DFK", "edge of box"],
        "tags": ["law-12", "penalty", "outside-box"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12 + Law 14", "year": 2024},
        "law_references": ["IFAB Law 12", "IFAB Law 14"],
        "outcome": "Direct FK (no pen)",
    },

    # ── GOAL-LINE & 2025/26 GK 8-SECOND — 4 cases ──
    {
        "title": "Goal-line — whole ball over the line (Law 10 goal)",
        "incident_type": "goal_line",
        "correct_decision": "Goal awarded — whole ball over whole line",
        "rationale": "Goal-line technology confirms the whole ball crossed the whole goal line. Law 10 clear and unambiguous — goal stands. No VAR intervention required beyond GLT confirmation.",
        "keywords": ["goal line technology", "GLT", "whole ball over line"],
        "tags": ["law-10", "goal-line", "GLT"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 10 + GLT", "year": 2024},
        "law_references": ["IFAB Law 10"],
        "outcome": "Goal awarded",
    },
    {
        "title": "Goal-line — ball partially over (NOT a goal)",
        "incident_type": "goal_line",
        "correct_decision": "No goal — ball not fully over line",
        "rationale": "Goal-line technology shows the ball was partially over the goal line but not fully. Law 10 requires the WHOLE ball to cross the WHOLE line. Play continues / restart as appropriate from where play was stopped.",
        "keywords": ["ball not over line", "no goal", "partial crossing", "Law 10"],
        "tags": ["law-10", "goal-line"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 10", "year": 2024},
        "law_references": ["IFAB Law 10"],
        "outcome": "No goal",
    },
    {
        "title": "GK 8-second rule — Corner kick to opposing team (2025/26)",
        "incident_type": "foul",
        "correct_decision": "Corner Kick to opposing team (GK 8-second violation)",
        "rationale": "2025/26 IFAB update: a goalkeeper who controls the ball with hands for more than 8 seconds is penalised by a CORNER KICK to the opposing team (replaces the old indirect free-kick). Referee counts down the last 5 seconds visibly. First major change to GK time-wasting in two decades.",
        "keywords": ["GK 8 seconds", "corner kick keeper", "2025-26", "time wasting keeper"],
        "tags": ["law-12", "goalkeeper", "2025-26", "time-wasting"],
        "match_context": {"teams": "Premier League Universal", "competition": "IFAB Law 12 (2025/26)", "year": 2025},
        "law_references": ["IFAB Law 12"],
        "outcome": "Corner kick",
    },
    {
        "title": "VAR protocol — mistaken identity yellow card (2025/26 expansion)",
        "incident_type": "other",
        "correct_decision": "Overturn yellow card — wrong player cautioned (VAR)",
        "rationale": "Referee booked the wrong player (case of mistaken identity during a crowd of players). 2025/26 VAR protocol expansion: VAR is now permitted to intervene for mistaken identity in YELLOW cards (previously red-only). Yellow rescinded and correctly-identified player is cautioned.",
        "keywords": ["mistaken identity", "wrong player booked", "VAR yellow 2025-26", "protocol expansion"],
        "tags": ["var-protocol", "mistaken-identity", "2025-26"],
        "match_context": {"teams": "Premier League Universal", "competition": "VAR Protocol (2025/26)", "year": 2025},
        "law_references": ["VAR Protocol"],
        "outcome": "Yellow rescinded + correct player cautioned",
    },

    # ── VAR PROTOCOL — 4 cases ──
    {
        "title": "VAR — subjective foul outside C&O bar (on-field decision stands)",
        "incident_type": "other",
        "correct_decision": "On-field decision stands — subjective, not clear-and-obvious",
        "rationale": "On-field referee adjudged a soft contact as a foul; VAR reviewed multiple angles and judged the degree-of-contact question subjective. 'Clear and obvious error' threshold not met. VAR protocol dictates on-field decision stands. This is a matters-of-degree call, not a factual error.",
        "keywords": ["on-field stands", "clear and obvious", "subjective foul", "VAR threshold"],
        "tags": ["var-protocol", "on-field-stands"],
        "match_context": {"teams": "Premier League Universal", "competition": "VAR Protocol", "year": 2024},
        "law_references": ["VAR Protocol"],
        "outcome": "On-field stands",
    },
    {
        "title": "VAR — second yellow wrongly issued (2025/26 expansion)",
        "incident_type": "other",
        "correct_decision": "Second yellow / red rescinded — VAR intervention (2025/26)",
        "rationale": "Player was shown a second yellow (=red) for a challenge that, on VAR review, was clearly not a cautionable offence. 2025/26 VAR protocol expansion permits intervention on clearly-wrong second yellows (previously not reviewable). Card rescinded.",
        "keywords": ["second yellow rescinded", "VAR 2025-26", "protocol expansion", "clearly wrong caution"],
        "tags": ["var-protocol", "second-yellow", "2025-26"],
        "match_context": {"teams": "Premier League Universal", "competition": "VAR Protocol (2025/26)", "year": 2025},
        "law_references": ["VAR Protocol"],
        "outcome": "Card rescinded",
    },
    {
        "title": "VAR — clearly wrong corner awarded (2025/26, immediate review only)",
        "incident_type": "corner",
        "correct_decision": "Corner overturned → Goal Kick (VAR, 2025/26)",
        "rationale": "Corner was awarded but replays showed the ball last touched an attacker before going out. 2025/26 VAR protocol expansion: VAR may intervene for clearly wrong corner kick awards, BUT ONLY IF review is immediate (before the next phase of play) to preserve match flow. Corner overturned to goal kick.",
        "keywords": ["corner overturned", "VAR corner 2025-26", "immediate review", "last touch"],
        "tags": ["var-protocol", "corner", "2025-26"],
        "match_context": {"teams": "Premier League Universal", "competition": "VAR Protocol (2025/26)", "year": 2025},
        "law_references": ["VAR Protocol"],
        "outcome": "Corner → Goal Kick",
    },
    {
        "title": "VAR — referee announces decision over PA (2025/26 transparency)",
        "incident_type": "other",
        "correct_decision": "Verdict announced over stadium PA (VAR transparency opt-in)",
        "rationale": "After a lengthy VAR check, the on-field referee announced the decision and reasoning over the stadium public-address system. 2025/26 IFAB opt-in: competitions may allow referee announcements after reviews for transparency. This does not change the verdict — it improves communication.",
        "keywords": ["referee announcement", "PA system", "VAR transparency", "2025-26"],
        "tags": ["var-protocol", "transparency", "2025-26"],
        "match_context": {"teams": "Premier League Universal", "competition": "VAR Protocol (2025/26)", "year": 2025},
        "law_references": ["VAR Protocol"],
        "outcome": "Verdict announced",
    },

    # ── Free-data expansion batch (Feb 2026): canonical scenarios pulled from
    #    publicly-available IFAB/PGMOL referee training material so the
    #    precedent-RAG retrieval has stronger anchor cases per incident type.
    # ── Offside expansion (5) ──────────────────────────────
    {
        "title": "Toe-tip offside — semi-automated technology overrules naked eye",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside",
        "rationale": "Attacker's toe was 2cm beyond the second-last defender at the moment the ball was played. Calibrated SAOT line is binding — no benefit-of-doubt threshold under current IFAB Law 11 wording.",
        "keywords": ["toe", "marginal", "SAOT", "calibrated line", "2cm", "millimeters", "no benefit of doubt"],
        "tags": ["marginal-offside", "saot", "goal-disallowed"],
        "match_context": {"teams": "Premier League Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal overturned",
    },
    {
        "title": "Offside reset by deliberate save — keeper clearance",
        "incident_type": "offside",
        "correct_decision": "Onside - Goal Stands",
        "rationale": "Goalkeeper made a deliberate save which the rebounding attacker tucked home. Even though the attacker was in an offside position when the original shot was struck, a deliberate save by an opponent does NOT reset the phase under 2024/25 clarification — but a deliberate save by the GOALKEEPER specifically still does. Read the 2025/26 amendment carefully.",
        "keywords": ["deliberate save", "rebound", "keeper save", "phase reset", "2025-26 wording"],
        "tags": ["offside-reset", "rebound", "goal-stands"],
        "match_context": {"teams": "PL Universal", "competition": "Premier League", "year": 2024},
        "law_references": ["IFAB Law 11", "Law 11 amendment 2024/25"],
        "outcome": "goal confirmed",
    },
    {
        "title": "Interfering with an opponent — blocked vision but no contact",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside (Active)",
        "rationale": "Attacker stood directly in line with the goalkeeper's view of the ball without making contact. Per IFAB Law 11 'interfering with an opponent' clause, this is offside-active even without touching ball or defender.",
        "keywords": ["blocking vision", "interfering with opponent", "active offside", "line of sight", "no contact"],
        "tags": ["interference", "active-offside", "goal-disallowed"],
        "match_context": {"teams": "Italy Serie A Universal", "competition": "Serie A", "year": 2023},
        "law_references": ["IFAB Law 11 (Interfering with opponent)"],
        "outcome": "goal overturned",
    },
    {
        "title": "Offside not active — challenges defender for ball not from teammate",
        "incident_type": "offside",
        "correct_decision": "Onside - Play On",
        "rationale": "Attacker in offside position did not interfere with play because the ball came from a defender's deflection, not a teammate. Offside requires the ball to be played by a team-mate. Defender deflection does not trigger offside.",
        "keywords": ["defender deflection", "no team-mate pass", "no offside", "play on"],
        "tags": ["no-offside", "deflection", "play-on"],
        "match_context": {"teams": "Bundesliga Universal", "competition": "Bundesliga", "year": 2023},
        "law_references": ["IFAB Law 11 (Triggers)"],
        "outcome": "goal confirmed",
    },
    {
        "title": "Daylight visible on body — clearly onside",
        "incident_type": "offside",
        "correct_decision": "Onside - Goal Stands",
        "rationale": "Clear daylight visible between the attacker's hip and the second-last defender's body. SAOT line confirms ≥10cm gap. No subjective interpretation required.",
        "keywords": ["daylight", "clear onside", "10cm gap", "SAOT confirmed"],
        "tags": ["clear-onside", "saot", "goal-stands"],
        "match_context": {"teams": "PL Universal", "competition": "Premier League", "year": 2024},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal confirmed",
    },

    # ── Handball expansion (5) ─────────────────────────────
    {
        "title": "Defender hand-on-grass support — natural position",
        "incident_type": "handball",
        "correct_decision": "No Penalty - Natural Body Position",
        "rationale": "Defender slid to block; supporting hand on grass made body wider but in a justifiable, natural position for the action. Per 2024/25 clarification, supporting body weight is not 'making the body unnaturally bigger'.",
        "keywords": ["sliding tackle", "hand on grass", "supporting body", "natural", "justifiable"],
        "tags": ["natural-handball", "no-penalty", "defender"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 12 (Handball, 2024/25 clarification)"],
        "outcome": "play continues",
    },
    {
        "title": "Attacker accidental handball before goal — disallowed",
        "incident_type": "handball",
        "correct_decision": "Handball - Goal Disallowed (Attacker Phase)",
        "rationale": "Ball deflected off attacker's arm immediately before scoring. Under attacking-phase handball rule, even accidental handball by the goalscorer or the immediate creator disallows the goal — strict liability.",
        "keywords": ["attacking handball", "accidental", "immediate creator", "strict liability", "goal disallowed"],
        "tags": ["attacking-handball", "goal-disallowed"],
        "match_context": {"teams": "World Cup Universal", "competition": "FIFA WC", "year": 2022},
        "law_references": ["IFAB Law 12 (Attacker handball)"],
        "outcome": "goal overturned",
    },
    {
        "title": "Defender hand close to body, ball deflected onto it",
        "incident_type": "handball",
        "correct_decision": "No Penalty - Hand by Side",
        "rationale": "Ball struck defender's hand which was tucked at hip level alongside body. No unnatural extension, no movement toward ball. Consistent with 2024/25 IFAB intent: hand close to body is not punishable.",
        "keywords": ["hand by side", "no extension", "natural", "no penalty", "ricochet"],
        "tags": ["natural-handball", "no-penalty"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "play continues",
    },
    {
        "title": "Defender raised arm above shoulder — penalty",
        "incident_type": "handball",
        "correct_decision": "Penalty - Arm Above Shoulder",
        "rationale": "Defender's arm was raised above shoulder height when the ball struck it. Above-shoulder is automatically considered an unnatural position regardless of intent or distance. Penalty.",
        "keywords": ["above shoulder", "unnatural", "automatic penalty", "raised arm"],
        "tags": ["penalty", "above-shoulder", "handball"],
        "match_context": {"teams": "Champions League Universal", "competition": "UCL", "year": 2024},
        "law_references": ["IFAB Law 12 (Above shoulder)"],
        "outcome": "penalty awarded",
    },
    {
        "title": "Goalkeeper handball outside area — DOGSO red",
        "incident_type": "handball",
        "correct_decision": "Red Card - DOGSO (Goalkeeper Outside Area)",
        "rationale": "GK rushed off line and handled ball clearly outside the penalty area, denying an obvious goal-scoring opportunity. Direct red card for DOGSO; double-jeopardy relief does NOT apply because the offence is handball, not a foul attempting to play the ball.",
        "keywords": ["GK outside area", "handball", "DOGSO", "red card", "outside box"],
        "tags": ["DOGSO", "handball", "red-card", "GK"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2023},
        "law_references": ["IFAB Law 12 (DOGSO)", "Law 12 (GK handling)"],
        "outcome": "red card",
    },

    # ── Penalty area fouls (5) ──────────────────────────────
    {
        "title": "Trailing leg trip in box — clear penalty",
        "incident_type": "penalty",
        "correct_decision": "Penalty Awarded",
        "rationale": "Defender's trailing leg made contact with attacker's standing leg after the ball had moved away. Clear careless contact inside the penalty area. Yellow card for SPA only (no DOGSO if defenders covering goal).",
        "keywords": ["trailing leg", "trip", "penalty", "careless", "after the ball"],
        "tags": ["penalty", "foul", "trip"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "penalty awarded",
    },
    {
        "title": "Soft contact, attacker initiates — no penalty",
        "incident_type": "penalty",
        "correct_decision": "No Penalty - Simulation Considered",
        "rationale": "Attacker's body movement initiated all the contact; defender retracted his leg. Replay shows no impeding force and clear theatrical fall. Yellow card for simulation can apply if blatant.",
        "keywords": ["simulation", "initiated contact", "no foul", "theatrical", "yellow simulation"],
        "tags": ["simulation", "no-penalty", "yellow-card"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 12 (Simulation)"],
        "outcome": "no penalty + caution simulation",
    },
    {
        "title": "Shirt pull at corner — penalty (zero tolerance)",
        "incident_type": "penalty",
        "correct_decision": "Penalty Awarded - Holding",
        "rationale": "Defender clearly grabbed and pulled attacker's shirt during a corner. PGMOL and FIFA reaffirmed zero-tolerance on holding at set pieces (2024/25 directive). Penalty + caution.",
        "keywords": ["shirt pull", "holding", "corner", "set piece", "zero tolerance"],
        "tags": ["holding", "penalty", "set-piece"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 12 (Holding)", "PGMOL directive 2024/25"],
        "outcome": "penalty awarded + yellow",
    },
    {
        "title": "Goalkeeper challenge — fair save with body",
        "incident_type": "penalty",
        "correct_decision": "No Penalty - Fair Save",
        "rationale": "GK reached the ball first with hands or body; subsequent collision with attacker is consequence not foul. No penalty because the GK's primary action was a legitimate save.",
        "keywords": ["GK first to ball", "fair save", "consequence collision", "no foul"],
        "tags": ["no-penalty", "GK-save", "play-on"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "no penalty",
    },
    {
        "title": "Late challenge after ball gone — penalty",
        "incident_type": "penalty",
        "correct_decision": "Penalty Awarded - Late Challenge",
        "rationale": "Defender went through the attacker after the ball had been released. Speed and force category 'reckless' → yellow card minimum, with VAR-confirmed contact inside the area → penalty.",
        "keywords": ["late challenge", "reckless", "after ball", "penalty"],
        "tags": ["late-challenge", "penalty", "yellow-card"],
        "match_context": {"teams": "Bundesliga Universal", "competition": "Bundesliga", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "penalty + yellow",
    },

    # ── DOGSO with 4 D's analysis (4) ───────────────────────
    {
        "title": "DOGSO 4D's all met — straight red",
        "incident_type": "foul",
        "correct_decision": "Red Card - DOGSO",
        "rationale": "All four D's met: Distance to goal (close), Direction of play (toward goal), Distance to ball (controlled by attacker), Defenders (none between attacker and goal). Foul outside the penalty area → straight red, no double-jeopardy relief.",
        "keywords": ["DOGSO", "4 D's", "outside area", "red card", "no relief"],
        "tags": ["DOGSO", "red-card", "outside-box"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 12 (DOGSO)"],
        "outcome": "red card",
    },
    {
        "title": "SPA in box — yellow + penalty (double-jeopardy relief applies)",
        "incident_type": "foul",
        "correct_decision": "Yellow Card + Penalty (SPA, Genuine Attempt)",
        "rationale": "Defender made a genuine attempt to play the ball but committed SPA inside the box. 2025/26 wording: yellow + penalty (not red), because the foul was a genuine attempt to play the ball, not holding/pulling/pushing. Double-jeopardy relief.",
        "keywords": ["SPA", "double jeopardy", "yellow", "penalty", "genuine attempt"],
        "tags": ["SPA", "yellow-card", "penalty", "double-jeopardy"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 12 (DOGSO/SPA double-jeopardy 2024/25)"],
        "outcome": "yellow + penalty",
    },
    {
        "title": "DOGSO holding — red card (no relief)",
        "incident_type": "foul",
        "correct_decision": "Red Card - DOGSO via Holding",
        "rationale": "Defender held attacker's shirt to prevent goal-scoring opportunity inside the box. Holding offences in the box are NOT eligible for double-jeopardy relief — straight red regardless of position because no genuine attempt to play ball.",
        "keywords": ["DOGSO holding", "red card", "no relief", "in box"],
        "tags": ["DOGSO", "red-card", "holding", "no-relief"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 12 (Holding DOGSO)"],
        "outcome": "red card + penalty",
    },
    {
        "title": "DOGSO assessment fails — covering defender",
        "incident_type": "foul",
        "correct_decision": "Yellow Card - SPA Only",
        "rationale": "On replay, a covering defender was within 2m of the attacker. The 4-D 'Defenders' criterion fails — multiple defenders between attacker and goal — so DOGSO downgrades to SPA. Yellow card.",
        "keywords": ["covering defender", "4D fail", "SPA downgrade", "yellow"],
        "tags": ["SPA", "yellow-card", "DOGSO-downgrade"],
        "match_context": {"teams": "Champions League Universal", "competition": "UCL", "year": 2023},
        "law_references": ["IFAB Law 12 (DOGSO assessment)"],
        "outcome": "yellow card",
    },

    # ── Goal-line technology (3) ────────────────────────────
    {
        "title": "Goal-line technology confirms whole ball over",
        "incident_type": "goal_line",
        "correct_decision": "Goal Awarded - GLT Confirmed",
        "rationale": "Hawkeye/GLT signal received within 1s of the ball crossing the line. Whole of ball cleared the plane — goal awarded automatically with watch buzz to referee.",
        "keywords": ["goal line technology", "GLT", "Hawkeye", "whole ball", "watch buzz"],
        "tags": ["GLT", "goal-confirmed", "auto-decision"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 9", "GLT Protocol"],
        "outcome": "goal confirmed",
    },
    {
        "title": "GLT no-signal — VAR confirms ball did NOT cross",
        "incident_type": "goal_line",
        "correct_decision": "No Goal - VAR Confirmed",
        "rationale": "GLT did not signal goal. VAR review confirmed at least part of the ball remained on the goal line, so no goal. Match restarts with whatever decision the on-field ref made.",
        "keywords": ["no GLT signal", "ball on line", "VAR", "no goal"],
        "tags": ["GLT", "no-goal", "VAR-confirmed"],
        "match_context": {"teams": "World Cup Universal", "competition": "FIFA WC", "year": 2022},
        "law_references": ["IFAB Law 9", "GLT Protocol"],
        "outcome": "no goal",
    },
    {
        "title": "Defender on goal-line clearance — millimetres in front",
        "incident_type": "goal_line",
        "correct_decision": "No Goal - Cleared",
        "rationale": "GLT showed the ball was 3mm in front of the line when the defender's boot cleared it. Whole ball never crossed the goal line — no goal.",
        "keywords": ["3mm", "millimetres", "cleared on line", "no goal"],
        "tags": ["GLT", "no-goal", "cleared"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 9"],
        "outcome": "no goal",
    },

    # ── Misconduct & dissent (4) ────────────────────────────
    {
        "title": "Captain-only dissent rule — yellow card",
        "incident_type": "card",
        "correct_decision": "Yellow Card - Dissent (Non-Captain Approached Referee)",
        "rationale": "2024/25 IFAB rule: only the team captain may approach the referee to question a decision. Non-captain who approached received an automatic yellow card.",
        "keywords": ["captain only", "dissent", "yellow card", "approach referee", "2024-25 rule"],
        "tags": ["dissent", "yellow-card", "captain-only"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 12 (Dissent)", "Captain-only directive 2024/25"],
        "outcome": "yellow card",
    },
    {
        "title": "Stamp on opponent — violent conduct red",
        "incident_type": "card",
        "correct_decision": "Red Card - Violent Conduct",
        "rationale": "Player deliberately stamped on opponent's leg while ball was elsewhere. Violent conduct off-the-ball — direct red card. Suspension typically 3 matches, escalating with severity.",
        "keywords": ["stamp", "violent conduct", "off the ball", "red card"],
        "tags": ["violent-conduct", "red-card", "off-the-ball"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2023},
        "law_references": ["IFAB Law 12 (Violent Conduct)"],
        "outcome": "red card",
    },
    {
        "title": "Elbow to head — serious foul play red",
        "incident_type": "card",
        "correct_decision": "Red Card - Serious Foul Play",
        "rationale": "While contesting an aerial duel, player led with raised elbow and struck opponent's head with excessive force. Serious foul play (when ball is in play) → straight red.",
        "keywords": ["elbow", "head", "aerial duel", "SFP", "excessive force"],
        "tags": ["SFP", "red-card", "aerial-duel"],
        "match_context": {"teams": "Champions League Universal", "competition": "UCL", "year": 2024},
        "law_references": ["IFAB Law 12 (Serious Foul Play)"],
        "outcome": "red card",
    },
    {
        "title": "Spitting at opponent — instant red",
        "incident_type": "card",
        "correct_decision": "Red Card - Spitting",
        "rationale": "Player spat at an opponent during a confrontation. Specifically listed as a sending-off offence. Long suspension typically follows.",
        "keywords": ["spitting", "red card", "sending off", "confrontation"],
        "tags": ["spitting", "red-card", "misconduct"],
        "match_context": {"teams": "International Universal", "competition": "International", "year": 2023},
        "law_references": ["IFAB Law 12 (Spitting)"],
        "outcome": "red card",
    },

    # ── Set-piece + restart edges (4) ───────────────────────
    {
        "title": "Quick free-kick taken without referee whistle",
        "incident_type": "freekick",
        "correct_decision": "Free Kick Stands - Quick Taken",
        "rationale": "Referee did not require a whistle for this free-kick. Attacker was alert and took it quickly. Goal stands; defenders had time to retreat 9.15m if needed.",
        "keywords": ["quick free kick", "no whistle required", "alert", "play on"],
        "tags": ["free-kick", "quick-taken", "goal-stands"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 13"],
        "outcome": "goal awarded",
    },
    {
        "title": "Indirect free-kick incorrectly given as direct",
        "incident_type": "freekick",
        "correct_decision": "Goal Disallowed - Was Indirect",
        "rationale": "Referee initially signalled direct, but on review the offence (impeding without contact) is an indirect free-kick offence. Goal scored direct from the kick must be disallowed; restart with goal kick.",
        "keywords": ["indirect free kick", "impeding", "no direct goal", "restart goal kick"],
        "tags": ["indirect-FK", "goal-disallowed"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2023},
        "law_references": ["IFAB Law 13 (Indirect)"],
        "outcome": "goal overturned",
    },
    {
        "title": "Penalty re-taken — encroachment by attacker into box",
        "incident_type": "penalty",
        "correct_decision": "Penalty Re-taken (Goal Scored, Encroachment)",
        "rationale": "Goal was scored, but a teammate encroached significantly into the penalty area before the kick was taken. Per IFAB Law 14, when the goal is scored AND the offending team's player encroaches, the kick is retaken.",
        "keywords": ["encroachment", "penalty retake", "Law 14", "attacker into box"],
        "tags": ["penalty", "encroachment", "retake"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 14"],
        "outcome": "retake",
    },
    {
        "title": "Goalkeeper double-touch on penalty — retake/goal",
        "incident_type": "penalty",
        "correct_decision": "Penalty Re-taken (GK Off Line) or Goal Confirmed",
        "rationale": "GK saved penalty but came off line significantly before the ball was kicked. If the kick is missed/saved → retake. If the kick was scored → goal stands. 2024/25 wording is precise.",
        "keywords": ["GK off line", "double touch", "retake", "Law 14", "off line before kick"],
        "tags": ["penalty", "GK-off-line", "Law-14"],
        "match_context": {"teams": "PL Universal", "competition": "PL", "year": 2024},
        "law_references": ["IFAB Law 14"],
        "outcome": "retake or goal",
    },
]
