"""
OCTON VAR — 20 canonical VAR precedents.
Bootstraps the training corpus so the AI has binding precedent on day one.
Each case carries: title, incident_type, correct_decision, rationale, keywords,
tags, match_context, law_references, outcome.
"""
CANONICAL_CASES = [
    # ── Offside (4) ─────────────────────────────────────────
    {
        "title": "Armpit Offside - Sterling vs Villarreal",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside",
        "rationale": "Attacker's armpit was fractionally beyond the last defender at the moment the ball was played. Marginal but conclusive on semi-automated offside lines.",
        "keywords": ["semi-automated", "armpit", "marginal", "last defender", "through ball", "goal scored", "calibrated line"],
        "tags": ["marginal-offside", "semi-automated", "goal-disallowed"],
        "match_context": {"teams": "Man City vs Villarreal", "competition": "UEFA Champions League", "year": 2021},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal overturned",
    },
    {
        "title": "Played Onside by Defender - Alexander-Arnold",
        "incident_type": "offside",
        "correct_decision": "Onside - Goal Stands",
        "rationale": "Attacker appeared in an offside position but was played onside by a deliberate clearance from a defender. Deliberate play resets the offside phase.",
        "keywords": ["played onside", "deliberate clearance", "defender", "reset phase", "onside"],
        "tags": ["onside", "deliberate-play", "goal-stands"],
        "match_context": {"teams": "Liverpool vs Tottenham", "competition": "Premier League", "year": 2019},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal confirmed",
    },
    {
        "title": "Clear Daylight Offside - Set Piece Line",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside",
        "rationale": "Striker was more than a metre beyond the last defender when the ball was played. No interpretation needed — unambiguous call.",
        "keywords": ["daylight", "clear offside", "striker beyond", "metre beyond", "unambiguous"],
        "tags": ["clear-offside", "daylight", "goal-disallowed"],
        "match_context": {"teams": "Real Madrid vs Valencia", "competition": "La Liga", "year": 2022},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal overturned",
    },
    {
        "title": "Offside from Corner — Not Applicable",
        "incident_type": "offside",
        "correct_decision": "Onside - Goal Stands",
        "rationale": "There is no offside offence from a corner kick regardless of attacker position. On-field flag should be withdrawn.",
        "keywords": ["corner kick", "no offside", "not applicable", "header goal", "corner"],
        "tags": ["no-offside-rule", "corner", "goal-stands"],
        "match_context": {"teams": "Arsenal vs Chelsea", "competition": "Premier League", "year": 2020},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal confirmed",
    },

    # ── Handball (4) ────────────────────────────────────────
    {
        "title": "Arm Extended Away from Body - Goal Ruled Out",
        "incident_type": "handball",
        "correct_decision": "Handball - Goal Disallowed",
        "rationale": "Attacker's arm was clearly extended away from the body to intercept, making the body unnaturally bigger prior to scoring. Attacking-phase handball rule applies.",
        "keywords": ["arm extended", "body bigger", "attacking handball", "disallow goal", "unnatural"],
        "tags": ["arm-extended", "body-bigger", "attacking-handball", "goal-disallowed"],
        "match_context": {"teams": "France vs Tunisia", "competition": "World Cup", "year": 2022},
        "law_references": ["IFAB Law 12"],
        "outcome": "goal overturned",
    },
    {
        "title": "Ball-to-Hand from Close Range — No Handball",
        "incident_type": "handball",
        "correct_decision": "No Handball - Natural Position",
        "rationale": "Ball struck defender's arm from close range with the arm in a natural position by the side. No deliberate movement toward the ball.",
        "keywords": ["ball to hand", "close range", "natural position", "by the side", "deflection", "no handball"],
        "tags": ["ball-to-hand", "natural-position", "no-handball"],
        "match_context": {"teams": "Juventus vs Inter", "competition": "Serie A", "year": 2021},
        "law_references": ["IFAB Law 12"],
        "outcome": "play on",
    },
    {
        "title": "Handball in Box — Penalty",
        "incident_type": "handball",
        "correct_decision": "Penalty Awarded - Handball",
        "rationale": "Defender slid with arm fully extended outside body line to block the shot inside the penalty area. Clear handball offence, deliberate act of making body bigger.",
        "keywords": ["arm extended", "inside box", "blocked shot", "sliding", "body bigger", "penalty"],
        "tags": ["inside-box", "arm-extended", "blocked-shot", "penalty"],
        "match_context": {"teams": "Barcelona vs Sevilla", "competition": "La Liga", "year": 2023},
        "law_references": ["IFAB Law 12", "IFAB Law 14"],
        "outcome": "penalty awarded",
    },
    {
        "title": "Deflection off own Body to Arm — No Handball",
        "incident_type": "handball",
        "correct_decision": "No Handball - Own Body Deflection",
        "rationale": "Ball deflected off attacker's thigh onto his own arm immediately before scoring. Per 2021 IFAB amendment, only deliberate handball by scorer is penalised; accidental contact off own body is not.",
        "keywords": ["own body", "deflection", "thigh", "accidental", "scorer", "own arm"],
        "tags": ["own-body-deflection", "accidental", "goal-stands"],
        "match_context": {"teams": "Bayern vs Leipzig", "competition": "Bundesliga", "year": 2022},
        "law_references": ["IFAB Law 12"],
        "outcome": "goal confirmed",
    },

    # ── Foul / Penalty (4) ──────────────────────────────────
    {
        "title": "Tactical Foul Stopping Counter — Yellow Card",
        "incident_type": "foul",
        "correct_decision": "Yellow Card - Stopping Promising Attack",
        "rationale": "Defender committed a cynical trip near halfway line as attacker broke forward with numerical advantage. Stopping a promising attack = mandatory yellow.",
        "keywords": ["tactical foul", "counter-attack", "promising attack", "cynical", "yellow card", "trip", "halfway"],
        "tags": ["tactical-foul", "stopping-promising-attack", "yellow-card"],
        "match_context": {"teams": "Man Utd vs Liverpool", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "yellow card issued",
    },
    {
        "title": "Penalty - Trip Inside the Area",
        "incident_type": "penalty",
        "correct_decision": "Penalty Awarded",
        "rationale": "Defender made contact with attacker's trailing leg inside the penalty area with no prior touch on the ball. Clear trip, penalty and no card (not DOGSO).",
        "keywords": ["trip", "inside box", "penalty area", "trailing leg", "no ball contact", "penalty"],
        "tags": ["trip", "inside-box", "penalty", "no-card"],
        "match_context": {"teams": "PSG vs Marseille", "competition": "Ligue 1", "year": 2022},
        "law_references": ["IFAB Law 14"],
        "outcome": "penalty awarded",
    },
    {
        "title": "Simulation - Dive in Penalty Area",
        "incident_type": "penalty",
        "correct_decision": "No Penalty - Simulation, Yellow Card Attacker",
        "rationale": "Attacker initiated contact and went down theatrically with no meaningful defender contact. Simulation is sanctioned with a yellow card.",
        "keywords": ["dive", "simulation", "theatrical", "no contact", "initiated contact", "yellow card attacker"],
        "tags": ["simulation", "dive", "yellow-attacker", "no-penalty"],
        "match_context": {"teams": "Dortmund vs Leipzig", "competition": "Bundesliga", "year": 2021},
        "law_references": ["IFAB Law 14"],
        "outcome": "yellow to attacker",
    },
    {
        "title": "Holding Inside Box at Corner — Penalty",
        "incident_type": "penalty",
        "correct_decision": "Penalty Awarded - Shirt Pull",
        "rationale": "Defender grabbed attacker's shirt and pulled him to ground inside the area from a corner kick. Persistent holding offences in the box must be penalised.",
        "keywords": ["holding", "shirt pull", "corner kick", "inside box", "persistent", "grabbed shirt"],
        "tags": ["holding", "shirt-pull", "corner", "penalty"],
        "match_context": {"teams": "Atletico vs Real Madrid", "competition": "La Liga", "year": 2022},
        "law_references": ["IFAB Law 14"],
        "outcome": "penalty awarded",
    },

    # ── Red Card (4) ────────────────────────────────────────
    {
        "title": "Studs-Up Serious Foul Play — Red Card",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Serious Foul Play",
        "rationale": "Tackle made with studs up, at speed, above the ankle with excessive force — endangering the opponent's safety. Mandatory red card.",
        "keywords": ["studs up", "high boot", "excessive force", "endanger safety", "serious foul play", "red card"],
        "tags": ["studs-up", "serious-foul-play", "excessive-force", "red-card"],
        "match_context": {"teams": "Chelsea vs Arsenal", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "DOGSO — Professional Foul Outside Box",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Denying Obvious Goal-Scoring Opportunity",
        "rationale": "Last defender tripped attacker who was clean through on goal with no cover. DOGSO mandates red card (outside penalty area, no attempt to play ball).",
        "keywords": ["last defender", "DOGSO", "clear through", "professional foul", "no cover", "red card"],
        "tags": ["DOGSO", "last-defender", "red-card"],
        "match_context": {"teams": "Spurs vs Newcastle", "competition": "Premier League", "year": 2022},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "Violent Conduct Off the Ball — Red Card",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Violent Conduct",
        "rationale": "Player struck opponent with elbow off the ball in an aerial duel — deliberate, excessive force, not a genuine challenge. Violent conduct = red.",
        "keywords": ["elbow", "off the ball", "violent conduct", "aerial duel", "struck opponent", "deliberate"],
        "tags": ["violent-conduct", "elbow", "off-ball", "red-card"],
        "match_context": {"teams": "AC Milan vs Napoli", "competition": "Serie A", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "Reckless but Not Excessive — Yellow not Red",
        "incident_type": "red_card",
        "correct_decision": "Yellow Card - Reckless Challenge",
        "rationale": "Challenge was late and reckless but did not use excessive force or endanger safety. Yellow is appropriate; red would exceed the threshold.",
        "keywords": ["reckless", "late tackle", "not excessive", "yellow card", "not endangering"],
        "tags": ["reckless", "yellow-card", "not-serious-foul"],
        "match_context": {"teams": "Brentford vs Wolves", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 12"],
        "outcome": "yellow card issued",
    },
    {
        "title": "Physical Contact With Referee — Automatic Violent Conduct",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Violent Conduct (Referee Contact)",
        "rationale": "Any deliberate physical contact with a match official (push, shove, grab, strike, headbutt, kick, spit) is automatic violent conduct under IFAB Law 12. No discretion, no 'clear and obvious' threshold — straight red card. Confidence must be very high whenever the description explicitly states the player made contact with the referee, assistant referee or 4th official.",
        "keywords": ["pushed referee", "shoved referee", "grabbed referee", "struck referee", "referee contact", "physical contact official", "angry player", "aggression toward referee", "howled referee", "contact with linesman", "violent conduct official"],
        "tags": ["violent-conduct", "referee-contact", "automatic-red", "no-discretion", "red-card"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12 (binding)", "year": 2024},
        "law_references": ["IFAB Law 12", "IFAB Law 5"],
        "outcome": "red card issued",
    },
    {
        "title": "Stamping on Opponent — Serious Foul Play Red",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Serious Foul Play (Stamping)",
        "rationale": "Player deliberately stamped on opponent's leg/ankle while ball was not in playable range. Stamping uses excessive force and endangers the opponent's safety — mandatory red.",
        "keywords": ["stamped on", "stamp", "stamping", "endangered safety", "ball not playable", "excessive force"],
        "tags": ["stamping", "serious-foul-play", "excessive-force", "red-card"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },
    {
        "title": "Spitting at Opponent — Violent Conduct Red",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Violent Conduct (Spitting)",
        "rationale": "Spitting at any person (opponent, team-mate, match official, spectator) is automatic violent conduct under IFAB Law 12. Straight red card with no discretion.",
        "keywords": ["spat at", "spat on", "spit at", "spitting", "violent conduct", "automatic red"],
        "tags": ["spitting", "violent-conduct", "automatic-red", "red-card"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued",
    },

    # ── Goal Line (2) ───────────────────────────────────────
    {
        "title": "Goal-Line Technology — Ball Over",
        "incident_type": "goal_line",
        "correct_decision": "Goal Confirmed - Ball Fully Crossed Line",
        "rationale": "GLT confirmed whole of ball crossed whole of line by 3 cm before being cleared. Binary decision — goal stands.",
        "keywords": ["goal line technology", "GLT", "whole ball", "fully crossed", "cleared", "binary"],
        "tags": ["goal-line-tech", "ball-crossed", "goal-confirmed"],
        "match_context": {"teams": "England vs Germany", "competition": "World Cup", "year": 2010},
        "law_references": ["IFAB Law 10"],
        "outcome": "goal confirmed",
    },
    {
        "title": "No Goal — Ball Did Not Fully Cross",
        "incident_type": "goal_line",
        "correct_decision": "No Goal - Ball Not Fully Over Line",
        "rationale": "Keeper scooped ball back with small portion still on the line. Any part on or above line = not a goal.",
        "keywords": ["scooped back", "on the line", "not fully", "keeper saved", "no goal"],
        "tags": ["not-fully-over", "goal-denied", "keeper-scoop"],
        "match_context": {"teams": "Aston Villa vs Sheffield United", "competition": "Premier League", "year": 2020},
        "law_references": ["IFAB Law 10"],
        "outcome": "no goal",
    },

    # ── Other (2) ───────────────────────────────────────────
    {
        "title": "Mistaken Identity — Card Rescinded",
        "incident_type": "other",
        "correct_decision": "Card Reassigned to Correct Player",
        "rationale": "Referee booked wrong player amid a scuffle; VAR identified correct offender. Mistaken identity is one of the four VAR-reviewable categories.",
        "keywords": ["mistaken identity", "wrong player", "scuffle", "rescinded", "reassigned", "VAR review"],
        "tags": ["mistaken-identity", "rescinded", "VAR-intervention"],
        "match_context": {"teams": "Everton vs Leeds", "competition": "Premier League", "year": 2021},
        "law_references": ["VAR Protocol"],
        "outcome": "card reassigned",
    },
    {
        "title": "Clear and Obvious Threshold — On-Field Stands",
        "incident_type": "other",
        "correct_decision": "On-Field Decision Stands",
        "rationale": "Contact was marginal and evidence inconclusive. VAR threshold (clear and obvious error) not met — on-field referee's call must stand.",
        "keywords": ["clear and obvious", "threshold", "marginal", "inconclusive", "on-field stands", "check complete"],
        "tags": ["clear-and-obvious", "threshold-not-met", "on-field-stands"],
        "match_context": {"teams": "Inter vs Juventus", "competition": "Serie A", "year": 2023},
        "law_references": ["VAR Protocol"],
        "outcome": "on-field decision stands",
    },

    # ── Offside Interference Edge Cases (4) ─────────────────
    {
        "title": "Offside Interference — Blocking Goalkeeper's Line of Sight",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside Interference (Law 11)",
        "rationale": "Attacker in offside position stood directly in goalkeeper's line of sight as the shot was struck. Even without touching the ball, blocking the keeper's vision constitutes interference with an opponent under Law 11. Goal must be disallowed.",
        "keywords": ["offside interference", "line of sight", "blocked vision", "obstructed keeper", "passive offside became active", "shot from distance", "no touch but interfered"],
        "tags": ["offside-interference", "blocked-keeper-vision", "law-11", "goal-disallowed"],
        "match_context": {"teams": "Tottenham vs Leeds", "competition": "Premier League", "year": 2021},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal overturned",
    },
    {
        "title": "Offside Rebound from Goalkeeper Save — Goal Disallowed",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside (Rebound from Save)",
        "rationale": "Striker was in offside position when team-mate's shot was struck. Goalkeeper saved the shot and ball rebounded to the offside attacker who scored. A save does NOT reset the offside phase — only a deliberate play (not a save) by a defender resets it. Goal must be disallowed.",
        "keywords": ["rebound from save", "keeper save", "offside rebound", "save does not reset", "deliberate save", "no reset phase", "offside attacker scored"],
        "tags": ["rebound-offside", "save-no-reset", "law-11", "goal-disallowed"],
        "match_context": {"teams": "Bayern vs Dortmund", "competition": "Bundesliga", "year": 2022},
        "law_references": ["IFAB Law 11", "IFAB 2022 Deliberate Play Clarification"],
        "outcome": "goal overturned",
    },
    {
        "title": "Offside Reset by Deliberate Defensive Play (2022 Clarification)",
        "incident_type": "offside",
        "correct_decision": "Onside - Goal Stands (Deliberate Play Reset)",
        "rationale": "Defender saw the ball coming, was in control, had time and space, and deliberately played it (controlled clearance under no immediate pressure). Per IFAB 2022 clarification, a deliberate defensive play resets the offside phase — the previously offside attacker is now onside. Goal stands.",
        "keywords": ["deliberate play", "controlled clearance", "defender in control", "had time and space", "reset phase", "2022 clarification", "deliberate defensive"],
        "tags": ["deliberate-play-reset", "onside-after-reset", "law-11", "2022-clarification", "goal-stands"],
        "match_context": {"teams": "Newcastle vs Arsenal", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 11", "IFAB 2022 Deliberate Play Clarification"],
        "outcome": "goal confirmed",
    },
    {
        "title": "Offside Challenge for Ball — Active Interference",
        "incident_type": "offside",
        "correct_decision": "Goal Disallowed - Offside Interference (Challenge)",
        "rationale": "Offside-position attacker actively challenged a defender for a header on the goal-bound cross. Even though team-mate scored, the offside attacker's challenge for the ball constitutes interfering with an opponent. Active interference, goal disallowed.",
        "keywords": ["offside challenge", "competed for ball", "interfering with opponent", "challenged defender", "active offside", "header goal disallowed"],
        "tags": ["active-interference", "challenged-for-ball", "law-11", "goal-disallowed"],
        "match_context": {"teams": "Liverpool vs Aston Villa", "competition": "Premier League", "year": 2023},
        "law_references": ["IFAB Law 11"],
        "outcome": "goal overturned",
    },

    # ── DOGSO vs SPA Distinction (3) ────────────────────────
    {
        "title": "DOGSO Inside Box — Genuine Attempt to Play Ball (Yellow only)",
        "incident_type": "red_card",
        "correct_decision": "Yellow Card + Penalty (DOGSO Triple-Punishment Exception)",
        "rationale": "Defender committed foul inside the penalty area while making a genuine attempt to play the ball, denying an obvious goal-scoring opportunity. Per 2017 IFAB amendment, DOGSO inside the box becomes a yellow card (not red) when the foul is a genuine attempt to play the ball. Avoids 'triple punishment' (penalty + red + suspension). Penalty awarded, yellow card only.",
        "keywords": ["DOGSO in box", "genuine attempt", "trying to play ball", "triple punishment", "yellow not red", "2017 amendment", "downgraded card", "DOGSO exception"],
        "tags": ["DOGSO-inside-box", "genuine-attempt", "triple-punishment-rule", "yellow-card", "2017-amendment"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12 (binding)", "year": 2017},
        "law_references": ["IFAB Law 12", "IFAB 2017 DOGSO Amendment"],
        "outcome": "yellow card + penalty",
    },
    {
        "title": "DOGSO Inside Box — Holding/Pulling (Red Card)",
        "incident_type": "red_card",
        "correct_decision": "Red Card - DOGSO (Holding) + Penalty",
        "rationale": "Defender denied an obvious goal-scoring opportunity by holding/pulling the attacker's shirt inside the penalty area — NOT a genuine attempt to play the ball. The 2017 'genuine attempt' exception does NOT apply to holding, pushing, or shirt-pulling offences. Full DOGSO red card stands plus penalty.",
        "keywords": ["DOGSO holding", "shirt pull", "no genuine attempt", "not playing ball", "DOGSO red", "holding offence", "DOGSO standard"],
        "tags": ["DOGSO-inside-box", "no-genuine-attempt", "holding", "red-card", "penalty"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12", "IFAB 2017 DOGSO Amendment"],
        "outcome": "red card + penalty",
    },
    {
        "title": "SPA Outside Box — Yellow Card Only",
        "incident_type": "foul",
        "correct_decision": "Yellow Card - Stopping a Promising Attack (SPA)",
        "rationale": "Foul stopped a promising attack outside the penalty area but the attacker was not clean through (cover defender present, distance from goal, ball not under control). DOGSO criteria (4-point checklist) NOT met — only SPA. Yellow card, not red.",
        "keywords": ["SPA", "stopping promising attack", "not DOGSO", "cover defender", "yellow card", "outside box", "no clean through"],
        "tags": ["SPA", "not-DOGSO", "yellow-card", "cover-defender"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "yellow card issued",
    },

    # ── Handball Edge Cases (3) ─────────────────────────────
    {
        "title": "Handball Justifiable Position — Sliding Tackle (No Offence)",
        "incident_type": "handball",
        "correct_decision": "No Handball - Arm Supporting Body (Justifiable)",
        "rationale": "Defender's arm was on the ground supporting body weight during a sliding tackle when the ball struck it. Per IFAB Law 12, when a player's arm is in a position to support the body (e.g. when sliding, falling, or jumping for a header), it is NOT considered to have 'made the body unnaturally bigger'. No offence, play on.",
        "keywords": ["arm supporting body", "sliding tackle", "justifiable position", "supporting weight", "natural for action", "no handball offence", "body support"],
        "tags": ["arm-supporting-body", "justifiable-position", "natural-for-action", "no-handball"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "play on",
    },
    {
        "title": "Accidental Handball Leading to Team-mate Goal (No Offence — 2021+)",
        "incident_type": "handball",
        "correct_decision": "Goal Stands - Only Scorer's Deliberate Handball Counts (2021)",
        "rationale": "Ball deflected accidentally off attacker A's arm, then attacker B (different player, not the scorer) scored. Per 2021 IFAB amendment, only the scorer's own handball offence (or an immediately-preceding deliberate handball by the scorer) negates the goal. Accidental handball by a TEAM-MATE leading to a goal is no longer an offence. Goal stands.",
        "keywords": ["accidental handball team-mate", "different scorer", "2021 amendment", "deflection chain", "goal stands handball", "non-scorer accidental"],
        "tags": ["2021-amendment", "team-mate-handball", "non-scorer", "goal-stands"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12 (2021)", "year": 2021},
        "law_references": ["IFAB Law 12", "IFAB 2021 Handball Amendment"],
        "outcome": "goal confirmed",
    },
    {
        "title": "Goalkeeper Handling Outside Penalty Area — Indirect/Direct Free Kick",
        "incident_type": "handball",
        "correct_decision": "Direct Free Kick + Yellow Card (Goalkeeper Handled Outside PA)",
        "rationale": "Goalkeeper picked up / parried the ball outside their own penalty area. Per Law 12, goalkeepers may only handle inside their own PA. Outside PA = direct free kick offence; if it denies a promising attack or DOGSO, additional sanctions apply (YC for SPA, RC for DOGSO).",
        "keywords": ["keeper outside box", "goalkeeper handled outside area", "rushed out", "direct free kick", "keeper handball", "outside PA"],
        "tags": ["keeper-outside-PA", "direct-free-kick", "keeper-handball", "law-12"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "direct free kick",
    },

    # ── Penalty / Encroachment 2024 (2) ─────────────────────
    {
        "title": "Penalty Encroachment by Attacker — Retake / Indirect Free Kick (2024)",
        "incident_type": "penalty",
        "correct_decision": "Penalty Retaken (if missed) / Indirect FK to Defending Team (if scored)",
        "rationale": "Attacking team-mate encroached significantly into the penalty area before the kick was struck and was first to play the rebound after a save. Per 2024 IFAB amendment: if the encroaching attacker scores or plays the rebound first, the kick is retaken (or, on a successful kick, the goal is disallowed and an indirect free kick is awarded against the attacking team).",
        "keywords": ["encroachment attacker", "penalty retake", "encroached into box", "first to rebound", "2024 amendment", "indirect free kick", "penalty encroachment"],
        "tags": ["penalty-encroachment", "attacker-encroached", "retake", "2024-amendment"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 14 (2024)", "year": 2024},
        "law_references": ["IFAB Law 14", "IFAB 2024 Encroachment Update"],
        "outcome": "penalty retaken",
    },
    {
        "title": "Penalty Encroachment by Defender — Retake (if missed)",
        "incident_type": "penalty",
        "correct_decision": "Penalty Retaken (if missed) / Goal Stands (if scored)",
        "rationale": "Defending team-mate encroached into the penalty area before the kick. If the penalty is missed or saved, the kick is retaken. If the penalty is scored, the goal stands (no retake to the defender's advantage). Per IFAB Law 14.",
        "keywords": ["defender encroachment", "encroached defender", "penalty retake missed", "goal stands scored", "law 14", "defender into box"],
        "tags": ["penalty-encroachment", "defender-encroached", "retake-if-missed", "law-14"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 14", "year": 2024},
        "law_references": ["IFAB Law 14"],
        "outcome": "retake or goal stands",
    },

    # ── Second Yellow / Cumulative Cautions (1) ─────────────
    {
        "title": "Second Caution = Sending Off (Two Yellows)",
        "incident_type": "red_card",
        "correct_decision": "Red Card - Two Cautions in Same Match (Second Yellow)",
        "rationale": "Player committed a second cautionable offence after already receiving a yellow card earlier in the same match. Two cautions in the same match result in a sending-off (red card) per IFAB Law 12. Note: this is a 'second yellow red' which carries a one-match suspension (lighter than a straight red).",
        "keywords": ["second yellow", "two cautions", "two yellows", "second booking", "cumulative caution", "sending off two yellows", "second yellow red"],
        "tags": ["second-yellow", "two-cautions", "red-card", "law-12"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "red card issued (second yellow)",
    },

    # ── Foul / Reckless vs SFP threshold (1) ────────────────
    {
        "title": "Hard Tackle With Some Reckless Elements — Yellow (Threshold not crossed)",
        "incident_type": "foul",
        "correct_decision": "Yellow Card - Reckless Challenge (No SFP)",
        "rationale": "Player went into challenge firmly with some recklessness (slightly late, raised foot a fraction) but did NOT use excessive force, did NOT endanger the opponent's safety, and ball was within playable range. Crosses the 'reckless' line (yellow) but not the 'excessive force / endangers safety' line that would make it Serious Foul Play (red). Yellow only.",
        "keywords": ["hard tackle", "slight reckless", "not excessive force", "did not endanger", "ball in range", "yellow not red", "borderline yellow", "sfp threshold"],
        "tags": ["reckless", "yellow-card", "not-SFP", "threshold-borderline"],
        "match_context": {"teams": "Universal Precedent", "competition": "IFAB Law 12", "year": 2024},
        "law_references": ["IFAB Law 12"],
        "outcome": "yellow card issued",
    },
]
